PREP(createCtrlFromElement);
PREP(getCurrentWeapon);
PREP(info_gps);
PREP(info_salh);
PREP(isElementValid);
PREP(registerDefaultHud);
PREP(registerElement);
PREP(shouldAdjustHud);
PREP(showVehicleHud);
