PREP(determineIfFatal);
PREP(getTypeOfDamage);
PREP(handleIncapacitation);
PREP(interpolatePoints);
PREP(parseConfigForInjuries);
PREP(woundReceived);
PREP(woundsHandler);
PREP(woundsHandlerBurning);
PREP(woundsHandlerSQF);
