
//Pilot Helmets with Visors
HELMET_VISOR(rhsusf_hgu56p,rhsusf_hgu56p_visor);
HELMET_VISOR(rhsusf_hgu56p_mask,rhsusf_hgu56p_visor_mask);
HELMET_VISOR(rhsusf_hgu56p_mask_mo,rhsusf_hgu56p_visor_mask_mo);
HELMET_VISOR(rhsusf_hgu56p_mask_skull,rhsusf_hgu56p_visor_mask_skull);

HELMET_VISOR(rhsusf_hgu56p_black,rhsusf_hgu56p_visor_black);
HELMET_VISOR(rhsusf_hgu56p_mask_black,rhsusf_hgu56p_visor_mask_black);
HELMET_VISOR(rhsusf_hgu56p_mask_Empire_black,rhsusf_hgu56p_visor_mask_Empire_black);
HELMET_VISOR(rhsusf_hgu56p_mask_black_skull,rhsusf_hgu56p_visor_mask_black_skull);

HELMET_VISOR(rhsusf_hgu56p_green,rhsusf_hgu56p_visor_green);
HELMET_VISOR(rhsusf_hgu56p_mask_green,rhsusf_hgu56p_visor_mask_green);
HELMET_VISOR(rhsusf_hgu56p_mask_green_mo,rhsusf_hgu56p_visor_mask_green_mo);

HELMET_VISOR(rhsusf_hgu56p_mask_smiley,rhsusf_hgu56p_visor_mask_smiley);

HELMET_VISOR(rhsusf_hgu56p_tan,rhsusf_hgu56p_visor_tan);
HELMET_VISOR(rhsusf_hgu56p_mask_tan,rhsusf_hgu56p_visor_mask_tan);

HELMET_VISOR(rhsusf_hgu56p_pink,rhsusf_hgu56p_visor_pink);
HELMET_VISOR(rhsusf_hgu56p_mask_pink,rhsusf_hgu56p_visor_mask_pink);

HELMET_VISOR(rhsusf_hgu56p_saf,rhsusf_hgu56p_visor_saf);
HELMET_VISOR(rhsusf_hgu56p_mask_saf,rhsusf_hgu56p_visor_mask_saf);

HELMET_VISOR(rhsusf_hgu56p_white,rhsusf_hgu56p_visor_white);

HELMET_VISOR(rhsusf_hgu56p_usa,rhsusf_hgu56p_visor_usa);

//Combat Helmets with Goggles
HELMET_GOGGLES(rhsusf_ach_helmet_ocp,rhsusf_ach_helmet_ESS_ocp,rhs_ess_black);
HELMET_GOGGLES(rhsusf_ach_helmet_headset_ocp,rhsusf_ach_helmet_headset_ess_ocp,rhs_ess_black);
HELMET_GOGGLES(rhsusf_ach_helmet_headset_ocp_alt,rhsusf_ach_helmet_headset_ess_ocp_alt,rhs_ess_black);

HELMET_GOGGLES(rhsusf_ach_bare_tan,rhsusf_ach_bare_tan_ess,rhs_ess_black);
HELMET_GOGGLES(rhsusf_ach_bare_tan_headset,rhsusf_ach_bare_tan_headset_ess,rhs_ess_black);

HELMET_GOGGLES(rhsusf_ach_bare_des,rhsusf_ach_bare_des_ess,rhs_ess_black);
HELMET_GOGGLES(rhsusf_ach_bare_des_headset,rhsusf_ach_bare_des_headset_ess,rhs_ess_black);

HELMET_GOGGLES(rhsusf_ach_helmet_ucp,rhsusf_ach_helmet_ESS_ucp,rhs_ess_black);
HELMET_GOGGLES(rhsusf_ach_helmet_ucp_alt,rhsusf_ach_helmet_ESS_ucp_alt,rhs_ess_black);
HELMET_GOGGLES(rhsusf_ach_helmet_headset_ucp,rhsusf_ach_helmet_headset_ess_ucp,rhs_ess_black);
HELMET_GOGGLES(rhsusf_ach_helmet_headset_ucp_alt,rhsusf_ach_helmet_headset_ess_ucp_alt,rhs_ess_black);

HELMET_GOGGLES(rhsusf_ach_bare,rhsusf_ach_bare_ess,rhs_ess_black);
HELMET_GOGGLES(rhsusf_ach_bare_headset,rhsusf_ach_bare_headset_ess,rhs_ess_black);

HELMET_GOGGLES(rhsusf_ach_bare_semi,rhsusf_ach_bare_semi_ess,rhs_ess_black);
HELMET_GOGGLES(rhsusf_ach_bare_semi_headset,rhsusf_ach_bare_semi_headset_ess,rhs_ess_black);

HELMET_GOGGLES(rhsusf_ach_bare_wood,rhsusf_ach_bare_wood_ess,rhs_ess_black);
HELMET_GOGGLES(rhsusf_ach_bare_wood_headset,rhsusf_ach_bare_wood_headset_ess,rhs_ess_black);

HELMET_GOGGLES(rhsusf_cvc_alt_helmet,rhsusf_cvc_ess,rhs_ess_black);
HELMET_GOGGLES(rhsusf_cvc_green_alt_helmet,rhsusf_cvc_green_ess,rhs_ess_black);

HELMET_GOGGLES(rhsusf_lwh_helmet_marpatwd,rhsusf_lwh_helmet_marpatwd_blk_ess,rhs_ess_black);
HELMET_GOGGLES(rhsusf_lwh_helmet_marpatwd_headset_blk2,rhsusf_lwh_helmet_marpatwd_headset_blk,rhs_ess_black);

HELMET_GOGGLES(rhsusf_protech_helmet,rhsusf_protech_helmet_ess,rhs_ess_black);
HELMET_GOGGLES(rhsusf_protech_helmet_rhino,rhsusf_protech_helmet_rhino_ess,rhs_ess_black);