#define COMPONENT xm157
#define COMPONENT_BEAUTIFIED XM157 Fire Control Scope
#include "\z\ace\addons\main\script_mod.hpp"

// #define DEBUG_MODE_FULL
// #define DISABLE_COMPILE_CACHE
// #define ENABLE_PERFORMANCE_COUNTERS
// #define ENABLE_QUICK_TESTING
// #define CREATE_MOCK_PLATFORMS

#include "\z\ace\addons\main\script_macros.hpp"

#define RANGEFINDER_MAX 5000

#define IDC_SCOPE_OBJECT 7000
#define IDC_SCOPE_GROUP 7001
#define IDC_SCOPE_RETICLE 7201

#define IDC_SCREEN_OBJECT 8000
#define IDC_SCREEN_GROUP 8001
#define IDC_SCREEN_MENU_TEXT 8201
#define IDC_SCREEN_TEXT_UPPER_LEFT 8202
#define IDC_SCREEN_TEXT_UPPER_RIGHT 8203
#define IDC_SCREEN_RETICLE 8204

