stages:
  mark_for_closing:
     days: 30
     labels:
       - need more info
       - invalid
       - can't reproduce
       - wontfix
       - information required
     exclude:
       - marked for cleanup
     comment:
       - 'Hello @{author}! There has been no activity on this ticket for over a period of {days} days. I am automatically replying to let you know we will close this ticket within 1 week due to inactivity and consider this resolved.'
       - 'If you believe this is in error, please reply with the requested information.'
       - 'Thank you. :robot:'
     action:
       close: false
       comment: true
       assign_label:
         - marked for cleanup
  clean_up:
     days: 7
     labels:
       - marked for cleanup
     comment:
       - 'Hello @{author}! We have detected no activity for {days} days on this ticket. We therefore assume that the original reporter has lost interest or the issue has been resolved.'
       - 'Since we have marked this ticket for deletion, we will be closing it.'
       - 'If this has been closed in error, please create a comment below and we can reopen this issue. Note that you may need to provide additional information that was requested.'
       - 'Thank you. :robot:'
     action:
       close: true
       comment: true
       assign_label:
         - closed by bot
       remove_label:
         - marked for cleanup
  remind_about_old_ticket:
    days: 160
    labels:
      - bug
      - critical bug
    exclude:
      - need more info
      - invalid
      - can't reproduce
      - wontfix
      - information required
      - marked for cleanup
      - inactive
    comment:
      - 'Hello @acemod/maintainers. This ticket has been open for over {days} days without any activity.'
    action:
      comment: true
      assign_label:
       - inactive
