PREP(addDamageToUnit);
PREP(addStateHandler);
PREP(adjustPainLevel);
PREP(dev_watchMedicalStats);
PREP(displayTriageCard);
PREP(getUnitState);
PREP(handleIncapacitation);
PREP(moduleMedicalSettings);
PREP(setUnconsciousStatemachine);
