UNIFORM_SLEEVES(cwr3_b_fia_uniform_woodland,cwr3_b_fia_uniform_woodland_rolled);
UNIFORM_SLEEVES(cwr3_b_fia_uniform_woodland_olive,cwr3_b_fia_uniform_woodland_olive_rolled);
UNIFORM_SLEEVES(cwr3_b_uniform_ERDL,cwr3_b_uniform_ERDL_rolled);
UNIFORM_SLEEVES(cwr3_b_uniform_black_gloves,cwr3_b_uniform_black_rolled_gloves);
UNIFORM_SLEEVES(cwr3_b_uniform_dcu,cwr3_b_uniform_dcu_rolled);
UNIFORM_SLEEVES(cwr3_b_uniform_desert_6color,cwr3_b_uniform_desert_6color_rolled);
UNIFORM_SLEEVES(cwr3_b_uniform_m81_woodland_gloves_sf,cwr3_b_uniform_m81_woodland_rolled_gloves_sf);
UNIFORM_SLEEVES(cwr3_i_uniform_alpenflage,cwr3_i_uniform_alpenflage_rolled);
UNIFORM_SLEEVES(cwr3_o_fia_uniform_granite_khaki,cwr3_o_fia_uniform_granite_khaki_rolled);
UNIFORM_SLEEVES(cwr3_o_fia_uniform_ttsko_p,cwr3_o_fia_uniform_ttsko_p_rolled);
UNIFORM_SLEEVES(cwr3_o_uniform_m1969_barracks_collar,cwr3_o_uniform_m1969_barracks_rolled);
UNIFORM_SLEEVES(cwr3_o_uniform_m1969_collar,cwr3_o_uniform_m1969_rolled);

UNIFORM_GLOVES(cwr3_b_uniform_m81_woodland_early,cwr3_b_uniform_m81_woodland_gloves_early);

UNIFORM_GLOVES_ROLLED(cwr3_b_uniform_m65_og107,cwr3_b_uniform_m65_og107_gloves,cwr3_b_uniform_m65_og107_rolled,cwr3_b_uniform_m65_og107_rolled_gloves);
UNIFORM_GLOVES_ROLLED(cwr3_b_uniform_m65_woodland,cwr3_b_uniform_m65_woodland_gloves,cwr3_b_uniform_m65_woodland_rolled,cwr3_b_uniform_m65_woodland_rolled_gloves);
UNIFORM_GLOVES_ROLLED(cwr3_b_uniform_m65_woodland_early,cwr3_b_uniform_m65_woodland_early_gloves,cwr3_b_uniform_m65_woodland_early_rolled,cwr3_b_uniform_m65_woodland_early_rolled_gloves);
UNIFORM_GLOVES_ROLLED(cwr3_b_uniform_m81_woodland,cwr3_b_uniform_m81_woodland_gloves,cwr3_b_uniform_m81_woodland_rolled,cwr3_b_uniform_m81_woodland_rolled_gloves);
