HELMET_GOGGLES(cwr3_b_headgear_cvc,cwr3_b_headgear_cvc_goggles,cwr3_b_facewear_goggles);
HELMET_GOGGLES(cwr3_b_headgear_m1_erdl,cwr3_b_headgear_m1_goggles_erdl,cwr3_b_facewear_goggles);
HELMET_GOGGLES(cwr3_b_headgear_m1_mitchell,cwr3_b_headgear_m1_goggles_mitchell,cwr3_b_facewear_goggles);
HELMET_GOGGLES(cwr3_b_headgear_m1_woodland_army_1985,cwr3_b_headgear_m1_goggles_woodland_army_1985,cwr3_b_facewear_goggles);
HELMET_GOGGLES(cwr3_b_headgear_m1_woodland_army_early,cwr3_b_headgear_m1_goggles_woodland_army_early,cwr3_b_facewear_goggles);
HELMET_GOGGLES(cwr3_b_headgear_pasgt_dcu,cwr3_b_headgear_pasgt_dcu_goggles,cwr3_b_facewear_goggles);
HELMET_GOGGLES(cwr3_b_headgear_pasgt_dcu_rhino,cwr3_b_headgear_pasgt_dcu_rhino_goggles,cwr3_b_facewear_goggles);
HELMET_GOGGLES(cwr3_b_headgear_pasgt_desert_6color,cwr3_b_headgear_pasgt_desert_6color_goggles,cwr3_b_facewear_goggles);
HELMET_GOGGLES(cwr3_b_headgear_pasgt_desert_6color_rhino,cwr3_b_headgear_pasgt_desert_6color_rhino_goggles,cwr3_b_facewear_goggles);
HELMET_GOGGLES(cwr3_b_headgear_pasgt_m81_woodland,cwr3_b_headgear_pasgt_m81_woodland_goggles,cwr3_b_facewear_goggles);
HELMET_GOGGLES(cwr3_b_headgear_pasgt_m81_woodland_early,cwr3_b_headgear_pasgt_m81_woodland_goggles_early,cwr3_b_facewear_goggles);
HELMET_GOGGLES(cwr3_b_headgear_pasgt_m81_woodland_rhino,cwr3_b_headgear_pasgt_m81_woodland_rhino_goggles,cwr3_b_facewear_goggles);
HELMET_GOGGLES(cwr3_b_headgear_pasgt_winter,cwr3_b_headgear_pasgt_winter_goggles,cwr3_b_facewear_goggles);

HELMET_GOGGLES_NOCOMPONENT(cwr3_b_headgear_protec_full,cwr3_b_headgear_protec_full_goggles);
HELMET_GOGGLES_NOCOMPONENT(cwr3_b_headgear_protec_half,cwr3_b_headgear_protec_half_goggles);
HELMET_GOGGLES_NOCOMPONENT(cwr3_b_headgear_protec_half_headset,cwr3_b_headgear_protec_half_headset_goggles);

HELMET_VISOR(cwr3_o_headgear_zsh5,cwr3_o_headgear_zsh5_visor);

BOONIE_ROLLED(cwr3_i_headgear_boonie_alpenflage,cwr3_i_headgear_boonie_rolled_alpenflage);
BOONIE_ROLLED(cwr3_i_headgear_boonie_flecktarn,cwr3_i_headgear_boonie_rolled_flecktarn);
