class CfgFunctions {
  class ADDON {
    class ADDON {
      file = PATHTOF(functions\);
      class addActionEventHandler;
      class addActionMenuEventHandler;
      class addCameraEventHandler;
      class addCustomEventHandler;
      class addInfoDisplayEventHandler;
      class addMapMarkerCreatedEventHandler;
      class addInventoryDisplayLoadedEventHandler;
      class addScrollWheelEventHandler;
      class adminKick;
      class ambientBrightness;
      class applyForceWalkStatus;
      class binarizeNumber;
      class callCustomEventHandlers;
      class callCustomEventHandlersGlobal;
      class canGetInPosition;
      class canInteractWith;
      class canUseWeapon;
      class changeProjectileDirection;
      class checkPBOs;
      class claim;
      class closeDialogIfTargetMoves;
      class codeToLetter;
      class codeToString;
      class convertKeyCode;
      class currentChannel;
      class disableUserInput;
      class displayText;
      class displayTextPicture;
      class displayTextStructured;
      class doAnimation;
      class endRadioTransmission;
      class execPersistentFnc;
      class execRemoteFnc;
      class executePersistent;
      class filter;
      class fixLoweredRifleAnimation;
      class getCaptivityStatus;
      class getConfigCommander;
      class getConfigGunner;
      class getDefaultAnim;
      class getDoorTurrets;
      class getForceWalkStatus;
      class getHitPoints;
      class getHitPointsWithSelections;
      class getInPosition;
      class getMarkerType;
      class getName;
      class getNumberFromMissionSQM;
      class getPitchBankYaw;
      class getStringFromMissionSQM;
      class getTargetAzimuthAndInclination;
      class getTargetDistance;
      class getTargetObject;
      class getTurretCommander;
      class getTurretConfigPath;
      class getTurretCopilot;
      class getTurretGunner;
      class getTurretIndex;
      class getTurrets;
      class getTurretsFFV;
      class getTurretsOther;
      class getUavControlPosition;
      class getVehicleCargo;
      class getVehicleCodriver;
      class getVehicleCrew;
      class getWeaponAzimuthAndInclination;
      class getWeaponType;
      class getWindDirection;
      class goKneeling;
      class hadamardProduct;
      class interpolateFromArray;
      class inTransitionAnim;
      class isAutoWind;
      class isEngineer;
      class isEOD;
      class isInBuilding;
      class isMedic;
      class isPlayer;
      class isTurnedOut;
      class letterToCode;
      class map;
      class moduleCheckPBOs;
      class moduleLSDVehicles;
      class muteUnit;
      class numberToDigits;
      class numberToDigitsString;
      class onLoadRscDisplayChannel;
      class owned;
      class player;
      class playerSide;
      class progressBar;
      class queueAnimation;
      class readBooleanParameterFromModule;
      class readNumericParameterFromModule;
      class removeActionEventHandler;
      class removeActionMenuEventHandler;
      class removeCameraEventHandler;
      class removeCustomEventHandler;
      class removeInfoDisplayEventHandler;
      class removeInventoryDisplayLoadedEventHandler;
      class removeMapMarkerCreatedEventHandler;
      class removeScrollWheelEventHandler;
      class restoreVariablesJIP;
      class revertKeyCodeLocalized;
      class sanitizeString;
      class serverLog;
      class setCaptivityStatus;
      class setForceWalkStatus;
      class setKeyDefault;
      class setName;
      class setParameter;
      class setPitchBankYaw;
      class setVariableJIP;
      class stringToColoredText;
      class subString;
      class toBin;
      class toBitmask;
      class toHex;
      class toNumber;
      class unmuteUnit;
    };
  };
  class AGM_Debug {
    class AGM_Debug {
      file = "AGM_Core\functions\Debug";
      class exportConfig;
      class getChildren;
      class getDisplayConfigName;
      class log;
      class logControls;
      class logDisplays;
      class monitor;
      class showUser;
    };
  };
  class AGM_CuratorFix {
    class AGM_CuratorFix {
      file = "AGM_Core\functions\CuratorFix";
      class addUnloadEventhandler;
      class fixCrateContent;
    };
  };
};