//fnc_setToRender.sqf
#include "script_component.hpp"
// No idea what this function was for, it was autogenerated out of my WIP file...
private ["_options"];
_object = _this select 0;
_options = _this select 1;
