
PREP(canOpenMenu);
PREP(openMenu);
PREP(onMenuOpen);
PREP(onMenuClose);
PREP(collectActions);
PREP(collectActions3D);
PREP(modifyAction);
PREP(getTreatmentOptions);
PREP(handleUI_DisplayOptions);
PREP(handleUI_dropDownTriageCard);
PREP(module);
PREP(setTriageStatus);
PREP(updateActivityLog);
PREP(updateBodyImage);
PREP(updateIcons);
PREP(updateInformationLists);
PREP(updateQuickViewLog);
PREP(updateUIInfo);
