PREP(addChangeFuseItemContextMenuOptions);
PREP(altFlashbangInit);
PREP(damageEngineAndWheels);
PREP(flare);
PREP(flashbangExplosionEH);
PREP(flashbangThrownFuze);
PREP(incendiary);
PREP(nextMode);
PREP(throwGrenade);
