class CfgMovesBasic {// Import needed references
    class Actions;
    class Default;
    class HealBase;
    class HealBaseRfl;
    class DefaultDie;
    class StandBase;
    class AgonyBase;
    class AgonyBaseRfl;
    class InjuredMovedBase;
};

// Define the stamina value for the move states
class CfgMovesMaleSdr: CfgMovesBasic {
    class States {
        class AmovPercMstpSlowWrflDnon: StandBase {stamina = 0.4};
        class AidlPercMstpSlowWrflDnon_G0S: AmovPercMstpSlowWrflDnon {};
        class AmovPercMstpSrasWrflDnon: AmovPercMstpSlowWrflDnon {stamina = 0.3};
        class AovrPercMstpSrasWrflDf: AmovPercMstpSrasWrflDnon {stamina = -1};
        class AmovPknlMstpSlowWrflDnon: AmovPercMstpSlowWrflDnon {stamina = 0.6};
        class AmovPknlMstpSrasWrflDnon: AmovPknlMstpSlowWrflDnon {stamina = 0.4};
        class AmovPpneMstpSrasWrflDnon: AmovPercMstpSrasWrflDnon {stamina = 0.8};
        class AmovPercMstpSrasWpstDnon: StandBase {stamina = 0.4};
        class AmovPercMstpSlowWpstDnon: AmovPercMstpSrasWpstDnon {stamina = 0.6};
        class AmovPknlMstpSrasWpstDnon: AmovPercMstpSrasWpstDnon {stamina = 0.6};
        class AmovPknlMstpSlowWpstDnon: AmovPknlMstpSrasWpstDnon {stamina = 0.8};
        class AmovPpneMstpSrasWpstDnon: AmovPercMstpSrasWpstDnon {stamina = 1};
        class AmovPknlMstpSrasWlnrDnon: Default {stamina = 0.4};
        class AmovPercMstpSnonWnonDnon: StandBase {stamina = 0.8};
        class AmovPercMwlkSrasWrflDf: AmovPercMstpSrasWrflDnon {stamina = 0.2};
        class AmovPercMwlkSlowWrflDf: AmovPercMstpSlowWrflDnon {stamina = 0.3};
        class AmovPercMwlkSlowWrflDfl: AmovPercMwlkSlowWrflDf {};
        class AidlPercMstpSnonWnonDnon_G0S: AmovPercMstpSnonWnonDnon {};
        class AmovPknlMrunSrasWrflDf: AmovPknlMstpSrasWrflDnon {stamina = -0.4};
        class AmovPercMwlkSrasWpstDf: AmovPercMstpSrasWpstDnon {stamina = 0.3};
        class AmovPercMwlkSlowWpstDf: AmovPercMwlkSrasWpstDf {stamina = 0.5};
        class AidlPknlMstpSrasWpstDnon_G0S: AmovPknlMstpSrasWpstDnon {};
        class AmovPknlMwlkSrasWpstDf: AmovPknlMstpSrasWpstDnon {stamina = -0.15};
        class AmovPknlMstpSnonWnonDnon: AmovPercMstpSnonWnonDnon {stamina = 1};
        class AmovPknlMrunSnonWnonDf: AmovPknlMstpSnonWnonDnon {stamina = -0.2};
        class AmovPpneMrunSlowWrflDf: AmovPpneMstpSrasWrflDnon {stamina = -1};
        class AmovPpneMstpSrasWrflDnon_injured: AgonyBaseRfl {stamina = 0.5};
        class AmovPpneMstpSnonWnonDnon: AmovPercMstpSnonWnonDnon {stamina = 1};
        class AidlPknlMstpSrasWrflDnon_G0S: AmovPknlMstpSrasWrflDnon {};
        class TransAnimBase: Default {stamina = 0.5};
        class TransAnimBase_noIK: TransAnimBase {};
        class AmovPercMstpSrasWrflDnon_AmovPercMstpSrasWpstDnon: TransAnimBase {stamina = -0.5};
        class AmovPercMstpSrasWrflDnon_AmovPercMstpSrasWpstDnon_end: AmovPercMstpSrasWrflDnon_AmovPercMstpSrasWpstDnon {};
        class AmovPercMstpSrasWrflDnon_AmovPercMstpSrasWlnrDnon: TransAnimBase_noIK {stamina = -0.5};
        class AmovPercMstpSrasWrflDnon_AmovPercMstpSrasWlnrDnon_end: TransAnimBase {stamina = -0.5};
        class AmovPercMstpSrasWpstDnon_AmovPercMstpSrasWrflDnon: TransAnimBase {stamina = -0.5};
        class AmovPercMstpSrasWpstDnon_AmovPercMstpSrasWrflDnon_end: AmovPercMstpSrasWpstDnon_AmovPercMstpSrasWrflDnon {};
        class AmovPercMstpSrasWpstDnon_AmovPercMstpSrasWlnrDnon: TransAnimBase {stamina = -0.5};
        class AmovPercMstpSrasWpstDnon_AmovPercMstpSrasWlnrDnon_end: TransAnimBase {stamina = -0.5};
        class AmovPercMstpSrasWlnrDnon_AmovPercMstpSrasWrflDnon: TransAnimBase {stamina = -0.5};
        class AmovPercMstpSrasWlnrDnon_AmovPercMstpSrasWrflDnon_end: TransAnimBase {stamina = -0.5};
        class AmovPercMstpSrasWlnrDnon_AmovPercMstpSrasWpstDnon: TransAnimBase {stamina = -0.5};
        class AmovPercMstpSrasWlnrDnon_AmovPercMstpSrasWpstDnon_end: TransAnimBase {stamina = -0.5};
        class SprintBaseDf: StandBase {stamina = -0.5};
        class AmovPercMevaSrasWrflDf: SprintBaseDf {stamina = -1};
        class SprintCivilBaseDf: SprintBaseDf {};
        class AmovPercMevaSrasWpstDf: SprintCivilBaseDf {stamina = -0.8};
        class CutSceneAnimationBase: AmovPercMstpSnonWnonDnon {};
        class TestDance: AmovPercMstpSrasWrflDnon {stamina = 0.7};
        class LadderCivilStatic: StandBase {stamina = 0.4};
        class LadderCivilUpLoop: LadderCivilStatic {stamina = -0.4};
        class AswmPercMstpSnonWnonDnon: AmovPercMstpSrasWrflDnon {stamina = 0.2};
        class AsswPercMstpSnonWnonDnon: AswmPercMstpSnonWnonDnon {};
        class AbswPercMstpSnonWnonDnon: AswmPercMstpSnonWnonDnon {};
        class AdvePercMstpSnonWnonDnon: AmovPercMstpSrasWrflDnon {};
        class AdvePercMrunSnonWnonDf: AdvePercMstpSnonWnonDnon {stamina = -0.3};
        class AsdvPercMstpSnonWnonDnon: AmovPercMstpSrasWrflDnon {};
        class AsdvPercMrunSnonWnonDf: AsdvPercMstpSnonWnonDnon {stamina = -0.2};
        class AbdvPercMstpSnonWnonDnon: AmovPercMstpSrasWrflDnon {};
        class AbdvPercMrunSnonWnonDf: AbdvPercMstpSnonWnonDnon {stamina = 0.2};
        class AmovPercMstpSoptWbinDnon: AmovPercMstpSlowWrflDnon {};
        class AmovPknlMstpSoptWbinDnon: AmovPknlMstpSrasWrflDnon {};
        class AmovPknlMwlkSoptWbinDf: AmovPknlMstpSoptWbinDnon {stamina = -0.1};
        class AmovPknlMrunSnonWbinDf: AmovPknlMwlkSoptWbinDf {stamina = -0.2};
        class AmovPpneMstpSoptWbinDnon: AmovPpneMstpSrasWrflDnon {};
        class AmovPpneMwlkSoptWbinDf: AmovPpneMstpSoptWbinDnon {stamina = -0.3};
        class AwopPercMstpSoptWbinDnon_rfl: AmovPercMstpSlowWrflDnon {};
        class AmovPercMwlkSoptWbinDf_rfl: AwopPercMstpSoptWbinDnon_rfl {stamina = 0.1};
        class AmovPercMrunSnonWbinDf_rfl: AmovPercMwlkSoptWbinDf_rfl {stamina = -0.4};
        class AwopPknlMstpSoptWbinDnon_rfl: AmovPknlMstpSrasWrflDnon {};
        class AmovPknlMwlkSoptWbinDf_rfl: AwopPknlMstpSoptWbinDnon_rfl {stamina = 0.1};
        class AmovPknlMrunSnonWbinDf_rfl: AmovPknlMwlkSoptWbinDf_rfl {stamina = -0.4};
        class AwopPpneMstpSoptWbinDnon_rfl: AmovPpneMstpSrasWrflDnon {};
        class AmovPpneMwlkSoptWbinDf_rfl: AwopPpneMstpSoptWbinDnon_rfl {stamina = 0.1};
        class AmovPpneMrunSnonWbinDf_rfl: AmovPpneMwlkSoptWbinDf_rfl {stamina = -0.4};
        class AwopPercMstpSoptWbinDnon_pst: AmovPercMstpSlowWrflDnon {};
        class AmovPercMwlkSoptWbinDf_pst: AwopPercMstpSoptWbinDnon_pst {stamina = 0.1};
        class AmovPercMrunSnonWbinDf_pst: AmovPercMwlkSoptWbinDf_pst {stamina = -0.4};
        class AwopPknlMstpSoptWbinDnon_pst: AmovPknlMstpSrasWpstDnon {};
        class AmovPknlMwlkSoptWbinDf_pst: AwopPknlMstpSoptWbinDnon_pst {stamina = 0.1};
        class AmovPknlMrunSnonWbinDf_pst: AmovPknlMwlkSoptWbinDf_pst {stamina = -0.4};
        class AwopPpneMstpSoptWbinDnon_pst: AmovPpneMstpSrasWpstDnon {};
        class AmovPpneMwlkSoptWbinDf_pst: AwopPpneMstpSoptWbinDnon_pst {stamina = 0.1};
        class AmovPpneMrunSnonWbinDf_pst: AmovPpneMwlkSoptWbinDf_pst {stamina = -0.4};
        class AwopPercMstpSoptWbinDnon_lnr: AmovPercMstpSlowWrflDnon {};
        class AmovPercMwlkSoptWbinDf_lnr: AwopPercMstpSoptWbinDnon_lnr {stamina = 0.1};
        class AmovPercMrunSnonWbinDf_lnr: AmovPercMwlkSoptWbinDf_lnr {stamina = -0.4};
        class AwopPknlMstpSoptWbinDnon_lnr: AmovPknlMstpSrasWlnrDnon {};
        class AmovPknlMwlkSoptWbinDf_lnr: AwopPknlMstpSoptWbinDnon_lnr {stamina = 0.1};
        class AmovPknlMrunSnonWbinDf_lnr: AmovPknlMwlkSoptWbinDf_lnr {stamina = -0.4};
        class AwopPercMstpSoptWbinDnon_non: AmovPercMstpSlowWrflDnon {};
        class AmovPercMwlkSoptWbinDf_non: AwopPercMstpSoptWbinDnon_non {stamina = 0.1};
        class AmovPercMrunSnonWbinDf_non: AmovPercMwlkSoptWbinDf_non {stamina = -0.4};
        class AwopPknlMstpSoptWbinDnon_non: AmovPknlMstpSrasWpstDnon {};
        class AmovPknlMwlkSoptWbinDf_non: AwopPknlMstpSoptWbinDnon_non {stamina = 0.1};
        class AmovPknlMrunSnonWbinDf_non: AmovPknlMwlkSoptWbinDf_non {stamina = -0.4};
        class AwopPpneMstpSoptWbinDnon_non: AmovPpneMstpSrasWpstDnon {};
        class AmovPpneMwlkSoptWbinDf_non: AwopPpneMstpSoptWbinDnon_non {stamina = 0.1};
        class AmovPpneMrunSnonWbinDf_non: AmovPpneMwlkSoptWbinDf_non {stamina = -0.4};
        class AinjPpneMstpSnonWrflDnon: AmovPpneMstpSrasWrflDnon_injured {};
        class AmovPercMstpSlowWrflDnon_AcinPknlMwlkSlowWrflDb_1: Default {stamina = -0.2};
        class AcinPercMrunSrasWrflDf: InjuredMovedBase {stamina = -0.5};
        class AcinPknlMstpSrasWrflDnon_AcinPercMrunSrasWrflDnon: InjuredMovedBase {stamina = -1};
        class AinjPfalMstpSnonWrflDnon_carried_Up: AgonyBaseRfl {stamina = 0.5};
        class AmovPpneMstpSnonWnonDnon_injured: AgonyBase {stamina = 0.5};
        class AinjPpneMstpSnonWnonDnon: AmovPpneMstpSnonWnonDnon_injured {};
        class AmovPercMstpSnonWnonDnon_AcinPknlMwlkSnonWnonDb_1: Default {stamina = -0.2};
        class AcinPercMrunSnonWnonDf: InjuredMovedBase {stamina = -0.5};
        class AcinPknlMstpSnonWnonDnon_AcinPercMrunSnonWnonDnon: InjuredMovedBase {stamina = -1};
        class AinjPfalMstpSnonWnonDnon_carried_Up: AgonyBase {stamina = 0.5};
        class AmovPercMstpSrasWlnrDnon: AmovPknlMstpSrasWlnrDnon {stamina = 0.2};
        class AmovPercMstpSlowWlnrDnon: AmovPercMstpSrasWlnrDnon {};
        class AadjPknlMstpSrasWpstDup: AmovPknlMstpSrasWpstDnon {};
        class AadjPercMstpSrasWpstDup: AmovPercMstpSrasWpstDnon {};
        class AadjPknlMstpSrasWpstDright: AadjPknlMstpSrasWpstDup {};
        class AadjPercMstpSrasWpstDright: AadjPercMstpSrasWpstDup {};
        class AadjPknlMstpSrasWpstDdown: AadjPknlMstpSrasWpstDup {};
        class AadjPercMstpSrasWpstDdown: AadjPercMstpSrasWpstDup {};
        class ApanPercMstpSnonWnonDnon: AmovPercMstpSnonWnonDnon {};
        class ApanPknlMstpSnonWnonDnon: AmovPknlMstpSnonWnonDnon {};
        class ApanPpneMstpSnonWnonDnon: AmovPpneMstpSnonWnonDnon {};
        class DeadState: Default {stamina = 0.5};
        class Unconscious: Default {stamina = 0.5};
        class AinvPknlMstpSnonWnonDnon_medic: HealBase {stamina = -0.2};
        class AinvPknlMstpSnonWrflDnon_medicEnd: HealBaseRfl {stamina = -0.2};
        class AinvPknlMstpSnonWnonDnon_medic0: HealBase {stamina = -0.2};
        class AinvPknlMstpSnonWnonDr_medic4: HealBase {stamina = -0.2};
        class AinvPknlMstpSnonWnonDr_medic5: HealBase {stamina = -0.2};
        class AinvPknlMstpSnonWnonDnon_medic4: HealBase {stamina = -0.2};
        class AinvPknlMstpSnonWnonDnon_medic5: HealBase {stamina = -0.2};
        class AinvPknlMstpSnonWnonDr_medic0: HealBase {stamina = -0.2};
        class AinvPknlMstpSnonWnonDnon_medicUp0: HealBase {stamina = -0.2};
        class AinvPknlMstpSnonWnonDr_medicUp4: HealBase {stamina = -0.2};
        class AinvPknlMstpSnonWnonDr_medicUp5: HealBase {stamina = -0.2};
        class AinvPknlMstpSnonWnonDnon_medicUp4: HealBase {stamina = -0.2};
        class AinvPknlMstpSnonWnonDnon_medicUp5: HealBase {stamina = -0.2};
        class AinvPknlMstpSnonWnonDr_medicUp0: HealBase {stamina = -0.2};
        class AinvPknlMstpSnonWnonDnon_AinvPknlMstpSnonWnonDnon_medic: HealBase {stamina = -0.2};
        class AinvPknlMstpSnonWrflDnon_AinvPknlMstpSnonWrflDnon_medic: HealBaseRfl {stamina = -0.2};
        class AinvPknlMstpSnonWrflDnon_medic: HealBaseRfl {stamina = -0.2};
        class Crew: Default {stamina = 0.5};
        class BasicDriver: Default {stamina = 0.5};
        class BasicDriverDying: DefaultDie {stamina = 0.5};
        class BasicDriverOut: Default {stamina = 0.5};
        class BasicDriverOutDying: DefaultDie {stamina = 0.5};
        class BasicSittingGunner_Dead: DefaultDie {stamina = 0.5};
        class AovrPercMstpSlowWrflDf: AmovPercMstpSlowWrflDnon {stamina = -1};
        class AmovPercMstpSlowWrflDnon_turnL: AidlPercMstpSlowWrflDnon_G0S {stamina = 0.2};
        class AmovPercMstpSlowWrflDnon_turnR: AidlPercMstpSlowWrflDnon_G0S {stamina = 0.2};
        class AovrPercMrunSrasWrflDf: AovrPercMstpSrasWrflDf {stamina = -10};
        class AmovPknlMstpSrasWrflDnon_turnL: AmovPknlMstpSrasWrflDnon {stamina = 0.2};
        class AmovPknlMstpSrasWrflDnon_turnR: AmovPknlMstpSrasWrflDnon {stamina = 0.2};
        class AmovPercMstpSrasWpstDnon_turnL: AmovPercMstpSrasWpstDnon {stamina = 0.2};
        class AmovPercMstpSrasWpstDnon_turnR: AmovPercMstpSrasWpstDnon {stamina = 0.2};
        class AmovPknlMstpSrasWpstDnon_turnL: AmovPknlMstpSrasWpstDnon {stamina = 0.4};
        class AmovPknlMstpSrasWpstDnon_turnR: AmovPknlMstpSrasWpstDnon {stamina = 0.4};
        class AovrPercMstpSnonWnonDf: AmovPercMstpSnonWnonDnon {stamina = -2};
        class AmovPercMrunSlowWrflDf: AmovPercMstpSlowWrflDnon {stamina = -0.2};
        class AmovPercMtacSrasWrflDf: AmovPercMwlkSrasWrflDf {stamina = -0.5};
        class AmovPercMtacSlowWrflDf: AmovPercMwlkSlowWrflDf {stamina = -0.15};
        class AmovPercMtacSlowWrflDfl: AmovPercMwlkSlowWrflDfl {stamina = -0.15};
        class AmovPercMrunSrasWrflDf: AmovPercMstpSrasWrflDnon {stamina = -0.3};
        class AmovPercMwlkSnonWnonDf: AidlPercMstpSnonWnonDnon_G0S {stamina = 0.6};
        class AmovPercMrunSnonWnonDf: AmovPercMstpSnonWnonDnon {stamina = -0.1};
        class AmovPknlMwlkSrasWrflDf: AmovPknlMstpSrasWrflDnon {stamina = -0.25};
        class AmovPknlMtacSrasWrflDf: AmovPknlMrunSrasWrflDf {stamina = -0.6};
        class AmovPercMtacSlowWpstDf: AmovPercMwlkSlowWpstDf {stamina = 0};
        class AmovPercMtacSrasWpstDf: AmovPercMwlkSrasWpstDf {stamina = -0.2};
        class AmovPercMrunSrasWpstDf: AmovPercMstpSrasWpstDnon {stamina = -0.15};
        class AmovPknlMrunSrasWpstDf: AidlPknlMstpSrasWpstDnon_G0S {stamina = -0.3};
        class AmovPknlMtacSrasWpstDf: AmovPknlMwlkSrasWpstDf {stamina = -0.4};
        class AmovPknlMwlkSnonWnonDf: AmovPknlMrunSnonWnonDf {stamina = 0};
        class AmovPpneMevaSlowWrflDf: AmovPpneMrunSlowWrflDf {stamina = -1.4};
        class AmovPpneMsprSlowWrflDf_injured: AmovPpneMstpSrasWrflDnon_injured {stamina = -2.6};
        class AmovPercMstpSrasWlnrDnon_AmovPknlMstpSrasWlnrDnon: TransAnimBase {stamina = -0.6};
        class AmovPpneMstpSrasWlnrDnon_AmovPercMstpSrasWlnrDnon: TransAnimBase {stamina = -2};
        class AmovPercMstpSrasWlnrDnon_AmovPpneMstpSrasWlnrDnon: TransAnimBase {stamina = -0.8};
        class AmovPpneMstpSrasWlnrDnon_AmovPknlMstpSrasWlnrDnon: TransAnimBase {stamina = -1};
        class AmovPknlMstpSrasWlnrDnon_AmovPercMstpSrasWlnrDnon: TransAnimBase {stamina = -0.8};
        class AmovPercMstpSrasWlnrDnon_AmovPpneMstpSnonWnonDnon: TransAnimBase {stamina = -2};
        class AmovPercMstpSrasWrflDnon_AmovPknlMstpSrasWrflDnon: AmovPknlMstpSrasWrflDnon {stamina = -0.4};
        class AmovPercMstpSrasWrflDnon_AmovPpneMstpSrasWrflDnon: AmovPpneMstpSrasWrflDnon {stamina = -0.5};
        class AmovPercMsprSlowWrflDf_AmovPpneMstpSrasWrflDnon: TransAnimBase {stamina = -1};
        class AmovPercMrunSlowWrflDf_AmovPpneMstpSrasWrflDnon: AmovPercMstpSrasWrflDnon {stamina = -2};
        class AmovPercMrunSlowWrflDf_AmovPpneMstpSrasWrflDnon_end: AmovPpneMstpSrasWrflDnon {stamina = -2};
        class AmovPercMrunSlowWrflDf_AmovPpneMstpSrasWrflDnon_old: AmovPpneMstpSrasWrflDnon {stamina = -2};
        class AmovPknlMstpSrasWrflDnon_AmovPercMstpSrasWrflDnon: AmovPercMstpSrasWrflDnon {stamina = -0.6};
        class AmovPknlMstpSrasWrflDnon_AmovPpneMstpSrasWrflDnon: AmovPpneMstpSrasWrflDnon {stamina = -0.4};
        class AmovPpneMstpSrasWrflDnon_AmovPercMstpSrasWrflDnon: AmovPercMstpSrasWrflDnon {stamina = -2};
        class AmovPpneMstpSrasWrflDnon_AmovPercMsprSlowWrflDf: TransAnimBase {stamina = -2};
        class AmovPpneMstpSrasWrflDnon_AmovPknlMstpSrasWrflDnon: AmovPknlMstpSrasWrflDnon {stamina = -1};
        class AmovPercMstpSrasWpstDnon_AmovPknlMstpSrasWpstDnon: AmovPknlMstpSrasWpstDnon {stamina = -0.2};
        class AmovPercMsprSlowWpstDf_AmovPpneMstpSrasWpstDnon: TransAnimBase {stamina = -0.8};
        class AmovPercMstpSrasWpstDnon_AmovPpneMstpSrasWpstDnon: AmovPpneMstpSrasWpstDnon {stamina = -0.4};
        class AmovPknlMstpSrasWpstDnon_AmovPercMstpSrasWpstDnon: AmovPercMstpSrasWpstDnon {stamina = -0.4};
        class AmovPknlMstpSrasWpstDnon_AmovPpneMstpSrasWpstDnon: AmovPpneMstpSrasWpstDnon {stamina = -0.2};
        class AmovPpneMstpSrasWpstDnon_AmovPercMstpSrasWpstDnon: AmovPercMstpSrasWpstDnon {stamina = -1};
        class AmovPpneMstpSrasWpstDnon_AmovPknlMstpSrasWpstDnon: AmovPknlMstpSrasWpstDnon {stamina = -0.8};
        class AmovPpneMstpSrasWpstDnon_AmovPercMsprSlowWpstDf: TransAnimBase {stamina = -2};
        class AmovPercMstpSnonWnonDnon_AmovPknlMstpSnonWnonDnon: AmovPknlMstpSnonWnonDnon {stamina = -0.1};
        class AmovPercMsprSnonWnonDf_AmovPpneMstpSnonWnonDnon: TransAnimBase {stamina = -0.6};
        class AmovPercMsprSnonWnonDf_AmovPpneMstpSnonWnonDnon_2: AmovPpneMstpSnonWnonDnon {stamina = -2};
        class AmovPercMstpSnonWnonDnon_AmovPpneMstpSnonWnonDnon: AmovPpneMstpSnonWnonDnon {stamina = -0.6};
        class AmovPknlMstpSnonWnonDnon_AmovPercMstpSnonWnonDnon: AmovPercMstpSnonWnonDnon {stamina = -0.2};
        class AmovPknlMstpSnonWnonDnon_AmovPpneMstpSnonWnonDnon: AmovPpneMstpSnonWnonDnon {stamina = -0.1};
        class AmovPpneMstpSnonWnonDnon_AmovPercMstpSnonWnonDnon: AmovPercMstpSnonWnonDnon {stamina = -1};
        class AmovPpneMstpSnonWnonDnon_AmovPknlMstpSnonWnonDnon: AmovPknlMstpSnonWnonDnon {stamina = -0.4};
        class AmovPknlMstpSrasWrflDnon_AmovPknlMstpSrasWpstDnon: AmovPercMstpSrasWrflDnon_AmovPercMstpSrasWpstDnon {stamina = -1};
        class AmovPknlMstpSrasWrflDnon_AmovPknlMstpSrasWpstDnon_end: AmovPercMstpSrasWrflDnon_AmovPercMstpSrasWpstDnon_end {stamina = -1};
        class AmovPpneMstpSrasWrflDnon_AmovPpneMstpSrasWpstDnon: TransAnimBase {stamina = -1.5};
        class AmovPknlMstpSrasWrflDnon_AmovPknlMstpSrasWlnrDnon: AmovPercMstpSrasWrflDnon_AmovPercMstpSrasWlnrDnon {stamina = -1};
        class AmovPknlMstpSrasWrflDnon_AmovPknlMstpSrasWlnrDnon_end: AmovPercMstpSrasWrflDnon_AmovPercMstpSrasWlnrDnon_end {stamina = -1};
        class AmovPknlMstpSrasWpstDnon_AmovPknlMstpSrasWrflDnon: AmovPercMstpSrasWpstDnon_AmovPercMstpSrasWrflDnon {stamina = -1};
        class AmovPknlMstpSrasWpstDnon_AmovPknlMstpSrasWrflDnon_end: AmovPercMstpSrasWpstDnon_AmovPercMstpSrasWrflDnon_end {stamina = -1};
        class AmovPpneMstpSrasWpstDnon_AmovPpneMstpSrasWrflDnon: TransAnimBase {stamina = -1.5};
        class AmovPknlMstpSrasWpstDnon_AmovPknlMstpSrasWlnrDnon: AmovPercMstpSrasWpstDnon_AmovPercMstpSrasWlnrDnon {stamina = -1};
        class AmovPknlMstpSrasWpstDnon_AmovPknlMstpSrasWlnrDnon_end: AmovPercMstpSrasWpstDnon_AmovPercMstpSrasWlnrDnon_end {stamina = -1};
        class AmovPknlMstpSrasWlnrDnon_AmovPknlMstpSrasWrflDnon: AmovPercMstpSrasWlnrDnon_AmovPercMstpSrasWrflDnon {stamina = -1};
        class AmovPknlMstpSrasWlnrDnon_AmovPknlMstpSrasWrflDnon_end: AmovPercMstpSrasWlnrDnon_AmovPercMstpSrasWrflDnon_end {stamina = -1};
        class AmovPknlMstpSrasWlnrDnon_AmovPknlMstpSrasWpstDnon: AmovPercMstpSrasWlnrDnon_AmovPercMstpSrasWpstDnon {stamina = -1};
        class AmovPknlMstpSrasWlnrDnon_AmovPknlMstpSrasWpstDnon_end: AmovPercMstpSrasWlnrDnon_AmovPercMstpSrasWpstDnon_end {stamina = -1};
        class AmovPknlMevaSrasWrflDf: AmovPercMevaSrasWrflDf {stamina = -1.2};
        class AmovPpneMstpSrasWrflDnon_AmovPpneMevaSlowWrflDl: AmovPpneMstpSrasWrflDnon {stamina = -3};
        class AmovPknlMevaSrasWpstDf: AmovPercMevaSrasWpstDf {stamina = -1};
        class AmovPpneMstpSrasWpstDnon_AmovPpneMevaSlowWpstDl: AmovPpneMstpSrasWpstDnon {stamina = -2.5};
        class AmovPercMevaSnonWnonDf: SprintCivilBaseDf {stamina = -0.6};
        class AmovPknlMevaSnonWnonDf: SprintCivilBaseDf {stamina = -0.8};
        class AmovPercMstpSnonWnonDnon_exercisekneeBendA: CutSceneAnimationBase {stamina = -0.55};
        class AmovPercMstpSnonWnonDnon_exercisePushup: CutSceneAnimationBase {stamina = -0.5};
        class TestSurrender: TestDance {stamina = 1};
        class AwopPercMstpSgthWrflDnon_Start1: Default {stamina = -0.6};
        class AmovPercMrunSlowWrflDf_AmovPercMstpSrasWrflDnon_gthStart: Default {stamina = -0.6};
        class AmovPercMwlkSrasWrflDf_AmovPercMstpSrasWrflDnon_gthStart: Default {stamina = -0.6};
        class AwopPknlMstpSgthWrflDnon_Start: Default {stamina = -0.6};
        class AwopPpneMstpSgthWrflDnon_Fast_Start: Default {stamina = -0.6};
        class AwopPpneMstpSgthWpstDnon_Fast_Start: Default {stamina = -0.6};
        class AwopPpneMstpSgthWnonDnon_Fast_Start: Default {stamina = -0.6};
        class AwopPpneMstpSgthWrflDnon_Start: Default {stamina = -0.6};
        class AwopPercMstpSgthWpstDnon_Part1: Default {stamina = -0.6};
        class AmovPercMrunSlowWpstDf_AmovPercMstpSrasWpstDnon_gthStart: Default {stamina = -0.6};
        class AmovPercMwlkSrasWpstDf_AwopPercMrunSgthWnonDf_1: Default {stamina = -0.6};
        class AmovPercMwlkSrasWpstDf_AmovPercMstpSrasWpstDnon_gthStart: Default {stamina = -0.6};
        class AwopPknlMstpSgthWpstDnon_Part1: Default {stamina = -0.6};
        class AwopPpneMstpSgthWpstDnon_Part1: Default {stamina = -0.6};
        class AwopPercMstpSgthWnonDnon_start: Default {stamina = -0.6};
        class AmovPercMrunSnonWnonDf_AmovPercMstpSnonWnonDnon_gthStart: Default {stamina = -0.6};
        class AwopPpneMstpSgthWnonDnon_start: Default {stamina = -0.6};
        class LadderCivilDownLoop: LadderCivilUpLoop {stamina = 0};
        class AswmPercMstpSnonWnonDnon_goup: AswmPercMstpSnonWnonDnon {stamina = -0.4};
        class AswmPercMstpSnonWnonDnon_godown: AswmPercMstpSnonWnonDnon {stamina = -0.8};
        class AswmPercMstpSnonWnonDnon_putDown: AswmPercMstpSnonWnonDnon {stamina = -0.3};
        class AswmPercMrunSnonWnonDf: AswmPercMstpSnonWnonDnon {stamina = -0.6};
        class AswmPercMstpSnonWnonDnon_AswmPercMrunSnonWnonDf: AswmPercMstpSnonWnonDnon {stamina = -0.3};
        class AsswPercMstpSnonWnonDnon_goup: AsswPercMstpSnonWnonDnon {stamina = -0.1};
        class AsswPercMstpSnonWnonDnon_goDown: AsswPercMstpSnonWnonDnon {stamina = -0.1};
        class AsswPercMstpSnonWnonDnon_putDown: AsswPercMstpSnonWnonDnon {stamina = -0.1};
        class AsswPercMrunSnonWnonDf: AsswPercMstpSnonWnonDnon {stamina = -0.3};
        class AsswPercMstpSnonWnonDnon_AsswPercMrunSnonWnonDf: AsswPercMstpSnonWnonDnon {stamina = -0.1};
        class AbswPercMstpSnonWnonDnon_goup: AbswPercMstpSnonWnonDnon {stamina = -0.3};
        class AbswPercMstpSnonWnonDnon_goDown: AbswPercMstpSnonWnonDnon {stamina = -0.3};
        class AbswPercMstpSnonWnonDnon_putDown: AbswPercMstpSnonWnonDnon {stamina = -0.3};
        class AbswPercMrunSnonWnonDf: AbswPercMstpSnonWnonDnon {stamina = -0.3};
        class AbswPercMstpSnonWnonDnon_AbswPercMrunSnonWnonDf: AbswPercMstpSnonWnonDnon {stamina = -0.3};
        class AdvePercMstpSnonWnonDnon_GetInSDV: AdvePercMstpSnonWnonDnon {stamina = -0.5};
        class AdvePercMstpSnonWnonDnon_GetOutSDV: AdvePercMstpSnonWnonDnon {stamina = -0.5};
        class AdvePercMstpSnonWnonDnon_goup: AdvePercMstpSnonWnonDnon {stamina = -0.4};
        class AdvePercMstpSnonWnonDnon_godown: AdvePercMstpSnonWnonDnon {stamina = -0.8};
        class AmovPercMwlkSrasWrflDf_AdvePercMrunSnonWnonDf: AmovPercMstpSrasWrflDnon {stamina = -0.06};
        class AdvePercMstpSnonWnonDnon_turnL: AdvePercMstpSnonWnonDnon {stamina = 0.2};
        class AdvePercMstpSnonWnonDnon_turnR: AdvePercMstpSnonWnonDnon {stamina = 0.2};
        class AdvePercMwlkSnonWnonDf: AdvePercMstpSnonWnonDnon {stamina = 0.2};
        class AdvePercMtacSnonWnonDf: AdvePercMstpSnonWnonDnon {stamina = 0.2};
        class AdvePercMsprSnonWnonDf: AdvePercMrunSnonWnonDf {stamina = -0.8};
        class AmovPercMwlkSrasWrflDf_AdvePercMrunSnonWrflDf: AmovPercMstpSrasWrflDnon {stamina = -0.06};
        class AsdvPercMstpSnonWnonDnon_GetInSDV: AsdvPercMstpSnonWnonDnon {stamina = -0.5};
        class AsdvPercMstpSnonWnonDnon_GetOutSDV: AsdvPercMstpSnonWnonDnon {stamina = -0.5};
        class AsdvPercMstpSnonWnonDnon_goup: AsdvPercMstpSnonWnonDnon {stamina = -0.4};
        class AsdvPercMstpSnonWnonDnon_godown: AsdvPercMstpSnonWnonDnon {stamina = -0.8};
        class AsdvPercMstpSnonWnonDnon_turnL: AsdvPercMstpSnonWnonDnon {stamina = 0.2};
        class AsdvPercMstpSnonWnonDnon_turnR: AsdvPercMstpSnonWnonDnon {stamina = 0.2};
        class AsdvPercMwlkSnonWnonDf: AsdvPercMstpSnonWnonDnon {stamina = 0.2};
        class AsdvPercMtacSnonWnonDf: AsdvPercMstpSnonWnonDnon {stamina = 0.2};
        class AsdvPercMsprSnonWnonDf: AsdvPercMrunSnonWnonDf {stamina = -0.8};
        class AbdvPercMstpSnonWnonDnon_GetInSDV: AbdvPercMstpSnonWnonDnon {stamina = -0.06};
        class AbdvPercMstpSnonWnonDnon_GetOutSDV: AbdvPercMstpSnonWnonDnon {stamina = -0.06};
        class AbdvPercMstpSnonWnonDnon_goup: AbdvPercMstpSnonWnonDnon {stamina = -0.06};
        class AbdvPercMstpSnonWnonDnon_godown: AbdvPercMstpSnonWnonDnon {stamina = -0.06};
        class AbdvPercMstpSnonWnonDnon_turnL: AbdvPercMstpSnonWnonDnon {stamina = -0.06};
        class AbdvPercMstpSnonWnonDnon_turnR: AbdvPercMstpSnonWnonDnon {stamina = -0.06};
        class AbdvPercMwlkSnonWnonDf: AbdvPercMstpSnonWnonDnon {stamina = 0.2};
        class AbdvPercMtacSnonWnonDf: AbdvPercMstpSnonWnonDnon {stamina = 0.2};
        class AbdvPercMsprSnonWnonDf: AbdvPercMrunSnonWnonDf {stamina = -0.6};
        class AovrPercMstpSoptWbinDf: AmovPercMstpSoptWbinDnon {stamina = -2};
        class AmovPknlMevaSnonWbinDf: AmovPknlMrunSnonWbinDf {stamina = -0.8};
        class AmovPercMevaSnonWbinDf_rfl: AmovPercMrunSnonWbinDf_rfl {stamina = -1};
        class AmovPknlMevaSnonWbinDf_rfl: AmovPknlMrunSnonWbinDf_rfl {stamina = -1};
        class AmovPpneMevaSnonWbinDf_rfl: AmovPpneMrunSnonWbinDf_rfl {stamina = -1};
        class AmovPercMevaSnonWbinDf_pst: AmovPercMrunSnonWbinDf_pst {stamina = -1};
        class AmovPknlMevaSnonWbinDf_pst: AmovPknlMrunSnonWbinDf_pst {stamina = -1};
        class AmovPpneMevaSnonWbinDf_pst: AmovPpneMrunSnonWbinDf_pst {stamina = -1};
        class AmovPercMevaSnonWbinDf_lnr: AmovPercMrunSnonWbinDf_lnr {stamina = -1};
        class AmovPknlMevaSnonWbinDf_lnr: AmovPknlMrunSnonWbinDf_lnr {stamina = -1};
        class AmovPercMevaSnonWbinDf_non: AmovPercMrunSnonWbinDf_non {stamina = -1};
        class AmovPknlMevaSnonWbinDf_non: AmovPknlMrunSnonWbinDf_non {stamina = -1};
        class AmovPpneMevaSnonWbinDf_non: AmovPpneMrunSnonWbinDf_non {stamina = -1};
        class AmovPercMstpSoptWbinDnon_AmovPknlMstpSoptWbinDnon: AmovPknlMstpSoptWbinDnon {stamina = -0.1};
        class AmovPercMstpSoptWbinDnon_AmovPpneMstpSoptWbinDnon: AmovPpneMstpSoptWbinDnon {stamina = -0.6};
        class AmovPknlMstpSoptWbinDnon_AmovPercMstpSoptWbinDnon: AmovPercMstpSoptWbinDnon {stamina = -0.2};
        class AmovPknlMstpSoptWbinDnon_AmovPpneMstpSoptWbinDnon: AmovPpneMstpSoptWbinDnon {stamina = -0.1};
        class AmovPpneMstpSoptWbinDnon_AmovPercMstpSoptWbinDnon: AmovPercMstpSoptWbinDnon {stamina = -1};
        class AmovPpneMstpSoptWbinDnon_AmovPknlMstpSoptWbinDnon: AmovPknlMstpSoptWbinDnon {stamina = -0.6};
        class AinjPpneMstpSnonWrflDnon_injuredHealed: AinjPpneMstpSnonWrflDnon {stamina = 0};
        class AinjPpneMstpSnonWrflDnon_rolltoback: AinjPpneMstpSnonWrflDnon {stamina = -3};
        class AcinPknlMstpSrasWrflDnon: AmovPercMstpSlowWrflDnon_AcinPknlMwlkSlowWrflDb_1 {stamina = 0.3};
        class DraggerBase: Default {stamina = -0.2};
        class AcinPknlMwlkSlowWrflDb_AmovPercMstpSlowWrflDnon: AmovPercMstpSlowWrflDnon_AcinPknlMwlkSlowWrflDb_1 {stamina = 0.5};
        class AcinPknlMwlkSrasWrflDb: AmovPercMstpSlowWrflDnon_AcinPknlMwlkSlowWrflDb_1 {stamina = -0.6};
        class AcinPercMstpSrasWrflDnon: AcinPknlMstpSrasWrflDnon_AcinPercMrunSrasWrflDnon {stamina = 0.2};
        class AcinPercMrunSrasWrflDf_AmovPercMstpSlowWrflDnon: InjuredMovedBase {stamina = 0.5};
        class Helper_InjuredRfl: AgonyBaseRfl {stamina = 0.5};
        class AinjPfalMstpSnonWrflDnon_carried_still: AinjPfalMstpSnonWrflDnon_carried_Up {stamina = 0};
        class AinjPfalMstpSnonWrflDnon_carried_Down: AgonyBase {stamina = 0.5};
        class AmovPpneMsprSnonWnonDf_injured: AmovPpneMstpSnonWnonDnon_injured {stamina = -2.6};
        class AinjPpneMstpSnonWnonDnon_injuredHealed: AinjPpneMstpSnonWnonDnon {stamina = 0};
        class AinjPpneMstpSnonWnonDnon_rolltoback: AinjPpneMstpSnonWnonDnon {stamina = -3};
        class AcinPknlMstpSnonWnonDnon: AmovPercMstpSnonWnonDnon_AcinPknlMwlkSnonWnonDb_1 {stamina = 0.3};
        class AcinPknlMwlkSnonWnonDb_AmovPercMstpSnonWnonDnon: AmovPercMstpSnonWnonDnon_AcinPknlMwlkSnonWnonDb_1 {stamina = 0.5};
        class AcinPknlMwlkSnonWnonDb: AmovPercMstpSnonWnonDnon_AcinPknlMwlkSnonWnonDb_1 {stamina = -6};
        class AcinPercMstpSnonWnonDnon: AcinPknlMstpSnonWnonDnon_AcinPercMrunSnonWnonDnon {stamina = 0.2};
        class AcinPercMrunSnonWnonDf_AmovPercMstpSnonWnonDnon: InjuredMovedBase {stamina = 0.5};
        class AinjPfalMstpSnonWnonDnon_carried_still: AinjPfalMstpSnonWnonDnon_carried_Up {stamina = 0};
        class AinjPfalMstpSnonWnonDnon_carried_Down: AgonyBase {stamina = 0.5};
        class AidlPsitMstpSnonWnonDnon_ground00: StandBase {stamina = 0.5};
        class AovrPercMstpSrasWlnrDf: AmovPercMstpSrasWlnrDnon {stamina = -2};
        class AovrPercMstpSlowWlnrDf: AmovPercMstpSlowWlnrDnon {stamina = -2};
        class AmovPercMstpSrasWlnrDnon_turnL: AmovPercMstpSrasWlnrDnon {stamina = 0};
        class AmovPercMstpSrasWlnrDnon_turnR: AmovPercMstpSrasWlnrDnon {stamina = 0};
        class AadjPercMstpSrasWpstDright_AadjPknlMstpSrasWpstDright: AadjPknlMstpSrasWpstDright {stamina = -0.3};
        class AadjPknlMstpSrasWpstDright_AadjPercMstpSrasWpstDright: AadjPercMstpSrasWpstDright {stamina = -0.3};
        class AadjPercMstpSrasWpstDdown_AadjPknlMstpSrasWpstDdown: AadjPknlMstpSrasWpstDdown {stamina = -0.3};
        class AadjPercMstpSrasWpstDdown_AadjPknlMstpSrasWpstDup: AadjPknlMstpSrasWpstDup {stamina = -0.3};
        class AadjPknlMstpSrasWpstDdown_AadjPercMstpSrasWpstDdown: AadjPercMstpSrasWpstDdown {stamina = -0.3};
        class AadjPercMstpSrasWpstDup_AadjPknlMstpSrasWpstDup: AadjPknlMstpSrasWpstDup {stamina = -0.3};
        class AadjPknlMstpSrasWpstDup_AadjPercMstpSrasWpstDup: AadjPercMstpSrasWpstDup {stamina = -0.3};
        class AadjPknlMstpSrasWpstDup_AadjPercMstpSrasWpstDdown: AadjPercMstpSrasWpstDdown {stamina = -0.3};
        class AadjPpneMstpSrasWpstDup_AadjPknlMstpSrasWpstDdown: AadjPknlMstpSrasWpstDdown {stamina = -0.3};
        class HaloFreeFall_non: Default {stamina = 0.5};
        class ReloadGM6: Default {stamina = 0.5};
        class MountOptic: Default {stamina = 0.5};
        class DismountOptic: Default {stamina = 0.5};
        class MountSide: Default {stamina = 0.5};
        class DismountSide: Default {stamina = 0.5};
        class HubTemplateU: StandBase {stamina = 0.5};
        class Mortar_01_F_Dead: DefaultDie {stamina = 0.5};
        class Static_Dead: DefaultDie {stamina = 0.5};
        class Mk201_Dead: DefaultDie {stamina = 0.5};
        class Mk34_Dead: DefaultDie {stamina = 0.5};
        class KIA_chopperLight_L_01_H: DefaultDie {stamina = 0.5};
        class KIA_ChopperHeavy_R_01_H: DefaultDie {stamina = 0.5};
        class KIA_RHIB_Driver: DefaultDie {stamina = 0.5};
        class KIA_RHIB_Cargo: DefaultDie {stamina = 0.5};
        class KIA_Zodiac_Driver: DefaultDie {stamina = 0.5};
        class KIA_Zodiac_Cargo_1: DefaultDie {stamina = 0.5};
        class KIA_Zodiac_Cargo_2: DefaultDie {stamina = 0.5};
        class KIA_Zodiac_Cargo_3: DefaultDie {stamina = 0.5};
        class KIA_Zodiac_Cargo_4: DefaultDie {stamina = 0.5};
        class KIA_Truck_02_Driver: DefaultDie {stamina = 0.5};
        class KIA_Truck_Driver: DefaultDie {stamina = 0.5};
        class KIA_Driver_High01: DefaultDie {stamina = 0.5};
        class KIA_Driver_low01: DefaultDie {stamina = 0.5};
        class KIA_Driver_mid01: DefaultDie {stamina = 0.5};
        class KIA_driver_Van_01: DefaultDie {stamina = 0.5};
        class KIA_pilot_Heli_Transport_01: DefaultDie {stamina = 0.5};
        class KIA_gunner_Heli_Transport_01: DefaultDie {stamina = 0.5};
        class KIA_driver_hemtt: DefaultDie {stamina = 0.5};
        class KIA_driver_ugv_01: DefaultDie {stamina = 0.5};
        class KIA_driver_Truck_02: DefaultDie {stamina = 0.5};
        class KIA_driver_Truck_03: DefaultDie {stamina = 0.5};
        class KIA_driver_tractor: DefaultDie {stamina = 0.5};
        class KIA_driver_boat01: DefaultDie {stamina = 0.5};
        class KIA_commander_MRAP_03: DefaultDie {stamina = 0.5};
        class KIA_driver_MRAP_03: DefaultDie {stamina = 0.5};
        class KIA_driver_mantis: DefaultDie {stamina = 0.5};
        class KIA_commander_sdv: DefaultDie {stamina = 0.5};
        class KIA_driver_sdv: DefaultDie {stamina = 0.5};
        class KIA_gunner_MRAP_01: DefaultDie {stamina = 0.5};
        class KIA_gunner_static_low01: DefaultDie {stamina = 0.5};
        class KIA_gunner_staticlauncher: DefaultDie {stamina = 0.5};
        class KIA_gunner_mortar: DefaultDie {stamina = 0.5};
        class KIA_gunner_standup01: DefaultDie {stamina = 0.5};
        class KIA_gunner_MRAP_03: DefaultDie {stamina = 0.5};
        class KIA_passenger_mantisrear: DefaultDie {stamina = 0.5};
        class KIA_passenger_flatground: DefaultDie {stamina = 0.5};
        class KIA_passenger_flatground_generic: DefaultDie {stamina = 0.5};
        class KIA_passenger_apc_generic01: DefaultDie {stamina = 0.5};
        class KIA_passenger_apc_generic02: DefaultDie {stamina = 0.5};
        class KIA_passenger_apc_generic03: DefaultDie {stamina = 0.5};
        class KIA_passenger_apc_generic04: DefaultDie {stamina = 0.5};
        class KIA_passenger_apc_narrow_generic01: DefaultDie {stamina = 0.5};
        class KIA_passenger_apc_narrow_generic02: DefaultDie {stamina = 0.5};
        class KIA_passenger_apc_narrow_generic03: DefaultDie {stamina = 0.5};
        class KIA_passenger_generic01: DefaultDie {stamina = 0.5};
        class KIA_passenger_generic02: DefaultDie {stamina = 0.5};
        class KIA_passenger_MRAP_01_back: DefaultDie {stamina = 0.5};
        class KIA_passenger_MRAP_01_front: DefaultDie {stamina = 0.5};
        class KIA_passenger_VAN_codriver01: DefaultDie {stamina = 0.5};
        class KIA_passenger_VAN_codriver02: DefaultDie {stamina = 0.5};
        class KIA_passenger_low01: DefaultDie {stamina = 0.5};
        class KIA_passenger_quadbike: DefaultDie {stamina = 0.5};
        class KIA_passenger_boat_rightrear: DefaultDie {stamina = 0.5};
        class KIA_passenger_boat_holdleft: DefaultDie {stamina = 0.5};
        class KIA_passenger_boat_holdleft2: DefaultDie {stamina = 0.5};
        class KIA_passenger_boat_holdright: DefaultDie {stamina = 0.5};
        class KIA_passenger_boat_holdright2: DefaultDie {stamina = 0.5};
        class KIA_passenger_injured_medevac_truck01: DefaultDie {stamina = 0.5};
        class KIA_passenger_injured_medevac_truck02: DefaultDie {stamina = 0.5};
        class KIA_passenger_injured_medevac_truck03: DefaultDie {stamina = 0.5};
        class KIA_passenger_MRAP_03exgunner: DefaultDie {stamina = 0.5};
        class KIA_passenger_sdv: DefaultDie {stamina = 0.5};
        class KIA_pilot_Heli_Attack_01: DefaultDie {stamina = 0.5};
        class KIA_crew_tank01: DefaultDie {stamina = 0.5};
        class KIA_gunner_apcwheeled3_in: DefaultDie {stamina = 0.5};
        class KIA_Heli_Attack_01_Pilot: DefaultDie {stamina = 0.5};
        class KIA_Para_Pilot: DefaultDie {stamina = 0.5};
        class KIA_Heli_Light_02_Cargo: DefaultDie {stamina = 0.5};
        class KIA_Heli_Light_02_Pilot: DefaultDie {stamina = 0.5};
        class KIA_Heli_Light_02_Gunner: DefaultDie {stamina = 0.5};
        class pilot_Heli_Light_02_KIA: DefaultDie {stamina = 0.5};
        class copilot_Heli_Light_02_KIA: DefaultDie {stamina = 0.5};
        class pilot_Heli_Light_03_KIA: DefaultDie {stamina = 0.5};
        class copilot_Heli_Light_03_KIA: DefaultDie {stamina = 0.5};
        class KIA_Heli_Attack_02_Cargo: DefaultDie {stamina = 0.5};
        class KIA_Heli_Attack_02_Pilot: DefaultDie {stamina = 0.5};
        class KIA_Heli_Attack_02_Gunner: DefaultDie {stamina = 0.5};
        class KIA_Plane_Fighter_03_Pilot: DefaultDie {stamina = 0.5};
        class KIA_pilot_plane_cas_01: DefaultDie {stamina = 0.5};
        class KIA_pilot_plane_cas_02: DefaultDie {stamina = 0.5};
        class DefaultDieA3: DefaultDie {stamina = 0.5};
        class passenger_bench_1_Die: DefaultDie {stamina = 0.5};
        class passenger_inside_1_Die: DefaultDie {stamina = 0.5};
        class passenger_inside_2_Die: DefaultDie {stamina = 0.5};
        class passenger_inside_3_Die: DefaultDie {stamina = 0.5};
        class passenger_inside_4_Die: DefaultDie {stamina = 0.5};
        class passenger_boat_1_Die: DefaultDie {stamina = 0.5};
        class passenger_boat_2_Die: DefaultDie {stamina = 0.5};
        class passenger_boat_3_Die: DefaultDie {stamina = 0.5};
        class passenger_boat_4_Die: DefaultDie {stamina = 0.5};
        class passenger_flatground_1_Die: DefaultDie {stamina = 0.5};
        class passenger_flatground_2_Die: DefaultDie {stamina = 0.5};
        class passenger_flatground_3_Die: DefaultDie {stamina = 0.5};
        class passenger_flatground_4_Die: DefaultDie {stamina = 0.5};
        class vehicle_turnout_1_Die: DefaultDie {stamina = 0.5};
        class vehicle_turnout_2_Die: DefaultDie {stamina = 0.5};
        class vehicle_coshooter_1_Die: DefaultDie {stamina = 0.5};
        class vehicle_passenger_stand_1_Die: DefaultDie {stamina = 0.5};
        class KIA_pilot_Heli_Transport_03: DefaultDie {stamina = 0.5};
        class KIA_pilot_Heli_Transport_04: DefaultDie {stamina = 0.5};
        class ApanPercMrunSnonWnonDf: ApanPercMstpSnonWnonDnon {stamina = -0.1};
        class ApanPknlMrunSnonWnonDf: ApanPknlMstpSnonWnonDnon {stamina = -0.2};
        class ApanPpneMrunSnonWnonDf: ApanPpneMstpSnonWnonDnon {stamina = -0.3};
        class ApanPercMwlkSnonWnonDf: ApanPercMstpSnonWnonDnon {stamina = 0.6};
        class ApanPknlMwlkSnonWnonDf: ApanPknlMstpSnonWnonDnon {stamina = 0};
        class ApanPercMsprSnonWnonDf: ApanPercMstpSnonWnonDnon {stamina = -0.6};
        class ApanPknlMsprSnonWnonDf: ApanPknlMstpSnonWnonDnon {stamina = -0.8};
        class ApanPpneMsprSnonWnonDf: ApanPpneMstpSnonWnonDnon {stamina = -1};
        class ApanPercMstpSnonWnonDnon_ApanPknlMstpSnonWnonDnon: ApanPknlMstpSnonWnonDnon {stamina = -0.1};
        class ApanPercMstpSnonWnonDnon_ApanPpneMstpSnonWnonDnon: ApanPpneMstpSnonWnonDnon {stamina = -0.6};
        class ApanPknlMstpSnonWnonDnon_ApanPercMstpSnonWnonDnon: ApanPercMstpSnonWnonDnon {stamina = -0.2};
        class ApanPknlMstpSnonWnonDnon_ApanPpneMstpSnonWnonDnon: ApanPpneMstpSnonWnonDnon {stamina = -0.1};
        class ApanPpneMstpSnonWnonDnon_ApanPercMstpSnonWnonDnon: ApanPercMstpSnonWnonDnon {stamina = -1};
        class ApanPpneMstpSnonWnonDnon_ApanPknlMstpSnonWnonDnon: ApanPknlMstpSnonWnonDnon {stamina = -0.4};
        class KIA_Pilot_Plane_Civil_01: DefaultDie {stamina = 0.5};
        class KIA_Copilot_Plane_Civil_01: DefaultDie {stamina = 0.5};
        class KIA_Passenger_Plane_Civil_01_L: DefaultDie {stamina = 0.5};
        class KIA_Passenger_Plane_Civil_01_R: DefaultDie {stamina = 0.5};
        class AidlPercMstpSrasWrflDnon_G0S: AmovPercMstpSrasWrflDnon {};
        class AidlPknlMstpSlowWrflDnon_G0S: AmovPknlMstpSlowWrflDnon {};
        class AidlPpneMstpSrasWrflDnon_G0S: AmovPpneMstpSrasWrflDnon {};
        class AidlPercMstpSrasWpstDnon_G0S: AmovPercMstpSrasWpstDnon {};
        class AidlPercMstpSlowWpstDnon_G0S: AmovPercMstpSlowWpstDnon {};
        class AidlPknlMstpSlowWpstDnon_G0S: AmovPknlMstpSlowWpstDnon {};
        class AmovPknlMwlkSlowWpstDf: AidlPknlMstpSlowWpstDnon_G0S {stamina = -0.1};
        class AidlPpneMstpSrasWpstDnon_G0S: AmovPpneMstpSrasWpstDnon {};
        class AidlPknlMstpSrasWlnrDnon_G0S: AmovPknlMstpSrasWlnrDnon {};
        class AmovPpneMstpSrasWlnrDnon: AidlPknlMstpSrasWlnrDnon_G0S {stamina = 1.2};
        class AmovPknlMrunSlowWrflDf: AidlPknlMstpSlowWrflDnon_G0S {stamina = -0.3};
        class AmovPknlMrunSlowWrflDfl: AmovPknlMrunSlowWrflDf {};
        class AmovPknlMrunSlowWrflDl: AmovPknlMrunSlowWrflDfl {};
        class AmovPknlMrunSlowWrflDbl: AmovPknlMrunSlowWrflDfl {};
        class AmovPknlMrunSlowWrflDb: AmovPknlMrunSlowWrflDfl {};
        class AmovPknlMrunSlowWrflDbr: AmovPknlMrunSlowWrflDfl {};
        class AmovPknlMrunSlowWrflDr: AmovPknlMrunSlowWrflDfl {};
        class AmovPknlMrunSlowWrflDfr: AmovPknlMrunSlowWrflDfl {};
        class AmovPercMrunSlowWlnrDf: AidlPknlMstpSrasWlnrDnon_G0S {stamina = -0.3};
        class AmovPercMrunSlowWlnrDfr: AmovPercMrunSlowWlnrDf {};
        class AmovPpneMrunSlowWpstDf: AidlPpneMstpSrasWpstDnon_G0S {stamina = -0.8};
        class AidlPpneMstpSnonWnonDnon_G0S: AmovPpneMstpSnonWnonDnon {};
        class AmovPpneMrunSnonWnonDf: AidlPpneMstpSnonWnonDnon_G0S {stamina = -0.3};
        class AadjPknlMstpSrasWrflDup: AidlPknlMstpSrasWrflDnon_G0S {};
        class AadjPpneMstpSrasWrflDup: AidlPpneMstpSrasWrflDnon_G0S {};
        class AdvePercMstpSnonWrflDnon: AidlPercMstpSrasWrflDnon_G0S {};
        class AdvePercMrunSnonWrflDf: AdvePercMstpSnonWrflDnon {stamina = -0.6};
        class AsdvPercMstpSnonWrflDnon: AidlPercMstpSrasWrflDnon_G0S {};
        class AsdvPercMrunSnonWrflDf: AsdvPercMstpSnonWrflDnon {stamina = -0.4};
        class AbdvPercMstpSnonWrflDnon: AidlPercMstpSrasWrflDnon_G0S {};
        class AbdvPercMrunSnonWrflDf: AbdvPercMstpSnonWrflDnon {stamina = 0.2};
        class AmovPercMwlkSoptWbinDf: AmovPercMstpSoptWbinDnon {};
        class AmovPercMrunSnonWbinDf: AmovPercMwlkSoptWbinDf {stamina = -0.1};
        class AmovPpneMrunSnonWbinDf: AmovPpneMwlkSoptWbinDf {};
        class AwopPpneMstpSoptWbinDnon_lnr: AmovPpneMstpSrasWlnrDnon {};
        class AmovPpneMwlkSoptWbinDf_lnr: AwopPpneMstpSoptWbinDnon_lnr {stamina = 0.1};
        class AmovPpneMrunSnonWbinDf_lnr: AmovPpneMwlkSoptWbinDf_lnr {stamina = -0.4};
        class AcinPercMrunSrasWrflDf_death: AcinPercMrunSrasWrflDf {};
        class AcinPercMrunSnonWnonDf_death: AcinPercMrunSnonWnonDf {};
        class AidlPercMstpSrasWlnrDnon_G0S: AmovPercMstpSrasWlnrDnon {};
        class AadjPknlMstpSrasWrflDleft: AadjPknlMstpSrasWrflDup {};
        class AadjPercMstpSrasWrflDup: AidlPercMstpSrasWrflDnon_G0S {};
        class AadjPknlMstpSrasWrflDright: AadjPknlMstpSrasWrflDup {};
        class AadjPercMstpSrasWrflDright: AadjPercMstpSrasWrflDup {};
        class AadjPercMstpSrasWrflDdown: AadjPercMstpSrasWrflDup {};
        class AadjPknlMstpSrasWpstDleft: AadjPknlMstpSrasWpstDup {};
        class AadjPercMstpSrasWpstDleft: AadjPercMstpSrasWpstDup {};
        class AadjPpneMstpSrasWpstDup: AidlPpneMstpSrasWpstDnon_G0S {};
        class AmovPercMstpSrasWrflDnon_turnL: AidlPercMstpSrasWrflDnon_G0S {stamina = 0};
        class AmovPercMstpSrasWrflDnon_turnR: AidlPercMstpSrasWrflDnon_G0S {stamina = 0};
        class AmovPknlMstpSlowWrflDnon_turnL: AidlPknlMstpSlowWrflDnon_G0S {stamina = 0.4};
        class AmovPknlMstpSlowWrflDnon_turnR: AidlPknlMstpSlowWrflDnon_G0S {stamina = 0.4};
        class AmovPpneMstpSrasWrflDnon_turnL: AidlPpneMstpSrasWrflDnon_G0S {stamina = 0.6};
        class AmovPpneMstpSrasWrflDnon_turnR: AidlPpneMstpSrasWrflDnon_G0S {stamina = 0.6};
        class AovrPercMstpSrasWpstDf: AidlPercMstpSrasWpstDnon_G0S {stamina = -1};
        class AmovPercMstpSlowWpstDnon_turnL: AidlPercMstpSlowWpstDnon_G0S {stamina = 0.4};
        class AmovPercMstpSlowWpstDnon_turnR: AidlPercMstpSlowWpstDnon_G0S {stamina = 0.4};
        class AmovPknlMstpSlowWpstDnon_turnL: AidlPknlMstpSlowWpstDnon_G0S {stamina = 0.6};
        class AmovPknlMtacSlowWpstDf: AmovPknlMwlkSlowWpstDf {stamina = -0.2};
        class AmovPknlMrunSlowWpstDf: AmovPknlMwlkSlowWpstDf {stamina = -0.3};
        class AmovPpneMstpSrasWpstDnon_turnL: AidlPpneMstpSrasWpstDnon_G0S {stamina = 0.8};
        class AmovPpneMstpSrasWpstDnon_turnR: AidlPpneMstpSrasWpstDnon_G0S {stamina = 0.8};
        class ReloadRPGKneel: AidlPknlMstpSrasWlnrDnon_G0S {stamina = -0.6};
        class AmovPknlMstpSrasWlnrDnon_turnL: AidlPknlMstpSrasWlnrDnon_G0S {stamina = 0.2};
        class AmovPknlMstpSrasWlnrDnon_turnR: AidlPknlMstpSrasWlnrDnon_G0S {stamina = 0.2};
        class AmovPpneMrunSrasWlnrDf: AmovPpneMstpSrasWlnrDnon {stamina = -0.6};
        class AmovPknlMwlkSlowWrflDf: AidlPknlMstpSlowWpstDnon_G0S {stamina = -0.2};
        class AmovPknlMtacSlowWrflDf: AmovPknlMrunSlowWrflDf {stamina = -0.25};
        class AmovPknlMtacSlowWrflDfl: AmovPknlMrunSlowWrflDfl {stamina = -0.2};
        class AmovPknlMtacSlowWrflDl: AmovPknlMrunSlowWrflDl {stamina = -0.2};
        class AmovPknlMtacSlowWrflDbl: AmovPknlMrunSlowWrflDbl {stamina = -0.2};
        class AmovPknlMtacSlowWrflDb: AmovPknlMrunSlowWrflDb {stamina = -0.2};
        class AmovPknlMtacSlowWrflDbr: AmovPknlMrunSlowWrflDbr {stamina = -0.2};
        class AmovPknlMtacSlowWrflDr: AmovPknlMrunSlowWrflDr {stamina = -0.2};
        class AmovPknlMtacSlowWrflDfr: AmovPknlMrunSlowWrflDfr {stamina = -0.2};
        class AmovPknlMrunSrasWlnrDf: AmovPercMrunSlowWlnrDf {stamina = -0.5};
        class AmovPknlMrunSrasWlnrDfr: AmovPercMrunSlowWlnrDfr {stamina = -0.5};
        class AmovPercMevaSlowWlnrDf: AmovPercMrunSlowWlnrDf {stamina = -1.4};
        class AmovPknlMevaSlowWlnrDf: AmovPercMrunSlowWlnrDf {stamina = -1.6};
        class AmovPknlMwlkSrasWlnrDf: AidlPknlMstpSrasWlnrDnon_G0S {stamina = -0.3};
        class AmovPknlMtacSrasWlnrDf: AidlPknlMstpSrasWlnrDnon_G0S {stamina = -0.5};
        class AmovPpneMsprSlowWpstDf: AmovPpneMrunSlowWpstDf {stamina = -1.2};
        class AmovPpneMsprSnonWnonDf: AmovPpneMrunSnonWnonDf {stamina = -1};
        class AadjPknlMstpSrasWrflDdown_AadjPpneMstpSrasWrflDup: AadjPpneMstpSrasWrflDup {stamina = -0.2};
        class AmovPpneMstpSnonWnonDnon_AmovPpneMevaSnonWnonDl: AidlPpneMstpSnonWnonDnon_G0S {stamina = -2};
        class AmovPpneMstpSnonWnonDnon_AmovPpneMevaSnonWnonDr: AidlPpneMstpSnonWnonDnon_G0S {stamina = -2};
        class AdvePercMstpSnonWrflDnon_GetInSDV: AdvePercMstpSnonWrflDnon {stamina = -0.5};
        class AdvePercMstpSnonWrflDnon_GetOutSDV: AdvePercMstpSnonWrflDnon {stamina = -0.5};
        class AdvePercMstpSnonWrflDnon_goup: AdvePercMstpSnonWrflDnon {stamina = -0.6};
        class AdvePercMstpSnonWrflDnon_godown: AdvePercMstpSnonWrflDnon {stamina = -1};
        class AdvePercMstpSnonWrflDnon_turnL: AdvePercMstpSnonWrflDnon {stamina = 0.1};
        class AdvePercMstpSnonWrflDnon_turnR: AdvePercMstpSnonWrflDnon {stamina = 0.1};
        class AdvePercMwlkSnonWrflDf: AdvePercMstpSnonWrflDnon {stamina = 0.2};
        class AdvePercMtacSnonWrflDf: AdvePercMstpSnonWrflDnon {stamina = 0.2};
        class AdvePercMsprSnonWrflDf: AdvePercMrunSnonWrflDf {stamina = -1};
        class AsdvPercMstpSnonWrflDnon_GetInSDV: AsdvPercMstpSnonWrflDnon {stamina = -0.5};
        class AsdvPercMstpSnonWrflDnon_GetOutSDV: AsdvPercMstpSnonWrflDnon {stamina = -0.5};
        class AsdvPercMstpSnonWrflDnon_goup: AsdvPercMstpSnonWrflDnon {stamina = -0.6};
        class AsdvPercMstpSnonWrflDnon_godown: AsdvPercMstpSnonWrflDnon {stamina = -1};
        class AsdvPercMstpSnonWrflDnon_turnL: AsdvPercMstpSnonWrflDnon {stamina = 0.1};
        class AsdvPercMstpSnonWrflDnon_turnR: AsdvPercMstpSnonWrflDnon {stamina = 0.1};
        class AsdvPercMwlkSnonWrflDf: AsdvPercMstpSnonWrflDnon {stamina = 0.2};
        class AsdvPercMtacSnonWrflDf: AsdvPercMstpSnonWrflDnon {stamina = 0.2};
        class AsdvPercMsprSnonWrflDf: AsdvPercMrunSnonWrflDf {stamina = -0.6};
        class AbdvPercMstpSnonWrflDnon_GetInSDV: AbdvPercMstpSnonWrflDnon {stamina = -0.06};
        class AbdvPercMstpSnonWrflDnon_GetOutSDV: AbdvPercMstpSnonWrflDnon {stamina = -0.06};
        class AbdvPercMstpSnonWrflDnon_goup: AbdvPercMstpSnonWrflDnon {stamina = -0.06};
        class AbdvPercMstpSnonWrflDnon_godown: AbdvPercMstpSnonWrflDnon {stamina = -0.06};
        class AbdvPercMstpSnonWrflDnon_turnL: AbdvPercMstpSnonWrflDnon {stamina = -0.06};
        class AbdvPercMstpSnonWrflDnon_turnR: AbdvPercMstpSnonWrflDnon {stamina = -0.06};
        class AbdvPercMwlkSnonWrflDf: AbdvPercMstpSnonWrflDnon {stamina = 0.2};
        class AbdvPercMtacSnonWrflDf: AbdvPercMstpSnonWrflDnon {stamina = 0.2};
        class AbdvPercMsprSnonWrflDf: AbdvPercMrunSnonWrflDf {stamina = -0.6};
        class AmovPercMevaSnonWbinDf: AmovPercMrunSnonWbinDf {stamina = -0.6};
        class AmovPpneMevaSnonWbinDf: AmovPpneMrunSnonWbinDf {stamina = -1};
        class AmovPpneMevaSnonWbinDf_lnr: AmovPpneMrunSnonWbinDf_lnr {stamina = -1};
        class AcinPercMrunSrasWrflDf_agony: AcinPercMrunSrasWrflDf_death {stamina = -10};
        class AcinPercMrunSnonWnonDf_agony: AcinPercMrunSnonWnonDf_death {stamina = -10};
        class ReloadRPG: AidlPercMstpSrasWlnrDnon_G0S {stamina = -0.6};
        class AmovPercMwlkSrasWlnrDf: AidlPercMstpSrasWlnrDnon_G0S {stamina = 0.1};
        class AmovPercMtacSrasWlnrDf: AidlPercMstpSrasWlnrDnon_G0S {stamina = -0.5};
        class AmovPercMrunSrasWlnrDf: AmovPercMrunSlowWlnrDf {stamina = -0.4};
        class AadjPercMstpSrasWrflDleft_AadjPknlMstpSrasWrflDleft: AadjPknlMstpSrasWrflDleft {stamina = -0.3};
        class AadjPercMstpSrasWrflDright_AadjPknlMstpSrasWrflDright: AadjPknlMstpSrasWrflDright {stamina = -0.3};
        class AadjPknlMstpSrasWrflDright_AadjPercMstpSrasWrflDright: AadjPercMstpSrasWrflDright {stamina = -0.3};
        class AadjPercMstpSrasWrflDdown_AadjPknlMstpSrasWrflDup: AadjPknlMstpSrasWrflDup {stamina = -0.3};
        class AadjPknlMstpSrasWrflDdown_AadjPercMstpSrasWrflDdown: AadjPercMstpSrasWrflDdown {stamina = -0.3};
        class AadjPercMstpSrasWrflDup_AadjPknlMstpSrasWrflDup: AadjPknlMstpSrasWrflDup {stamina = -0.3};
        class AadjPknlMstpSrasWrflDup_AadjPercMstpSrasWrflDup: AadjPercMstpSrasWrflDup {stamina = -0.3};
        class AadjPknlMstpSrasWrflDup_AadjPercMstpSrasWrflDdown: AadjPercMstpSrasWrflDdown {stamina = -0.3};
        class AadjPercMstpSrasWpstDleft_AadjPknlMstpSrasWpstDleft: AadjPknlMstpSrasWpstDleft {stamina = -0.3};
        class AadjPknlMstpSrasWpstDleft_AadjPercMstpSrasWpstDleft: AadjPercMstpSrasWpstDleft {stamina = -0.3};
        class AadjPknlMstpSrasWpstDdown_AadjPpneMstpSrasWpstDup: AadjPpneMstpSrasWpstDup {stamina = -0.3};
        class AadjPknlMstpSrasWrflDdown: AadjPknlMstpSrasWrflDup {};
        class AadjPercMstpSrasWrflDleft: AadjPercMstpSrasWrflDup {};
        class AadjPpneMstpSrasWrflDup_AadjPknlMstpSrasWrflDdown: AadjPknlMstpSrasWrflDdown {stamina = -0.2};
        class AadjPknlMstpSrasWrflDleft_AadjPercMstpSrasWrflDleft: AadjPercMstpSrasWrflDleft {stamina = -0.3};
        class AadjPercMstpSrasWrflDdown_AadjPknlMstpSrasWrflDdown: AadjPknlMstpSrasWrflDdown {stamina = -0.3};
    };
};
