PREP(calculateMapScale);
PREP(canUseMapGPS);
PREP(canUseMapTools);
PREP(drawLinesOnRoamer);
PREP(handleMouseButton);
PREP(handleMouseMove);
PREP(isInsideMapTool);
PREP(openMapGpsUpdate);
PREP(updateMapToolMarkers);
