// COMPONENT should be defined in the script_component.hpp and included BEFORE this hpp

#define MAINPREFIX z
#define PREFIX ace

#define MAJOR 3
#define MINOR 0
#define PATCHLVL 0
#define BUILD 1

#define VERSION MAJOR.MINOR.PATCHLVL.BUILD
#define VERSION_AR MAJOR,MINOR,PATCHLVL,BUILD

#define ACE_TAG A.C.E.

// MINIMAL required version for the Mod. Components can specify others..
#define REQUIRED_VERSION 0.5

/*
	#define DEBUG_ENABLED_SYS_ADDONS
	#define DEBUG_ENABLED_SYS_ATTACHMENTS
	#define DEBUG_ENABLED_sys_weapons_backblast
	#define DEBUG_ENABLED_SYS_BLOOD
	#define DEBUG_ENABLED_SYS_CARTRIDGES
	#define DEBUG_ENABLED_SYS_CRATERS
	#define DEBUG_ENABLED_SYS_CREWPROTECTION
	#define DEBUG_ENABLED_SYS_DUMMIES
	#define DEBUG_ENABLED_SYS_EJECT
	#define DEBUG_ENABLED_SYS_EXPLOSIVES
	#define DEBUG_ENABLED_SYS_FLARES
	#define DEBUG_ENABLED_SYS_FLASHBANG
	#define DEBUG_ENABLED_SYS_GRENADETHROW
	#define DEBUG_ENABLED_SYS_HUNTIR
	#define DEBUG_ENABLED_SYS_INTERACTION
	#define DEBUG_ENABLED_SYS_IRSTROBE
	#define DEBUG_ENABLED_SYS_MULTI_BARREL
	#define DEBUG_ENABLED_SYS_MUZZLEBLAST
	#define DEBUG_ENABLED_SYS_NVG
	#define DEBUG_ENABLED_sys_weapons_overheating
	#define DEBUG_ENABLED_SYS_RECOILDUST
	#define DEBUG_ENABLED_SYS_ROCKET_BALLISTICS
	#define DEBUG_ENABLED_SYS_SANDBAG
	#define DEBUG_ENABLED_SYS_SHOTGUN
	#define DEBUG_ENABLED_SYS_SIGHT_ADJUSTMENT_AT
	#define DEBUG_ENABLED_SYS_SIGHT_ADJUSTMENT_GL
	#define DEBUG_ENABLED_SYS_SIGHT_ADJUSTMENT_RIFLE
	#define DEBUG_ENABLED_SYS_SMAW_SPOTTINGRIFLE
	#define DEBUG_ENABLED_SYS_TRACERS
	#define DEBUG_ENABLED_SYS_TRACKING
	#define DEBUG_ENABLED_SYS_VIEWBLOCK
	#define DEBUG_ENABLED_SYS_VEHICLE
	#define DEBUG_ENABLED_sys_vehicle_damage
	#define DEBUG_ENABLED_SYS_WEAPONREST
	#define DEBUG_ENABLED_SYS_WOUNDS
*/
