// COMPONENT should be defined in the script_component.hpp and included BEFORE this hpp

#define MAINPREFIX z
#define PREFIX ace

#define MAJOR 3
#define MINOR 0
#define PATCHLVL 0
#define BUILD 1

#define VERSION MAJOR.MINOR.PATCHLVL.BUILD
#define VERSION_AR MAJOR,MINOR,PATCHLVL,BUILD

#define ACE_TAG A.C.E.

// MINIMAL required version for the Mod. Components can specify others..
#define REQUIRED_VERSION 0.5

/*
    #define DEBUG_ENABLED_ADDONS
    #define DEBUG_ENABLED_ATTACHMENTS
    #define DEBUG_ENABLED_weapons_backblast
    #define DEBUG_ENABLED_BLOOD
    #define DEBUG_ENABLED_CARTRIDGES
    #define DEBUG_ENABLED_CRATERS
    #define DEBUG_ENABLED_CREWPROTECTION
    #define DEBUG_ENABLED_DUMMIES
    #define DEBUG_ENABLED_EJECT
    #define DEBUG_ENABLED_EXPLOSIVES
    #define DEBUG_ENABLED_FLARES
    #define DEBUG_ENABLED_FLASHBANG
    #define DEBUG_ENABLED_GRENADETHROW
    #define DEBUG_ENABLED_HUNTIR
    #define DEBUG_ENABLED_INTERACTION
    #define DEBUG_ENABLED_IRSTROBE
    #define DEBUG_ENABLED_MULTI_BARREL
    #define DEBUG_ENABLED_MUZZLEBLAST
    #define DEBUG_ENABLED_NVG
    #define DEBUG_ENABLED_weapons_overheating
    #define DEBUG_ENABLED_RECOILDUST
    #define DEBUG_ENABLED_ROCKET_BALLISTICS
    #define DEBUG_ENABLED_SANDBAG
    #define DEBUG_ENABLED_SHOTGUN
    #define DEBUG_ENABLED_SIGHT_ADJUSTMENT_AT
    #define DEBUG_ENABLED_SIGHT_ADJUSTMENT_GL
    #define DEBUG_ENABLED_SIGHT_ADJUSTMENT_RIFLE
    #define DEBUG_ENABLED_SMAW_SPOTTINGRIFLE
    #define DEBUG_ENABLED_TRACERS
    #define DEBUG_ENABLED_TRACKING
    #define DEBUG_ENABLED_VIEWBLOCK
    #define DEBUG_ENABLED_VEHICLE
    #define DEBUG_ENABLED_vehicle_damage
    #define DEBUG_ENABLED_WEAPONREST
    #define DEBUG_ENABLED_WOUNDS
*/
