#define     ICONS_GROUPTYPE             [ \
    [ \
        LOCALIZESTR(HELI), \
        "A3\ui_f\data\map\markers\nato\b_air.paa" \
    ], \
    [ \
        LOCALIZESTR(ARMORED), \
        "A3\ui_f\data\map\markers\nato\b_armor.paa" \
    ], \
    [ \
        LOCALIZESTR(ARTILLERY), \
        "A3\ui_f\data\map\markers\nato\b_art.paa" \
    ], \
    [ \
        LOCALIZESTR(HQ), \
        "A3\ui_f\data\map\markers\nato\b_hq.paa" \
    ], \
    [ \
        LOCALIZESTR(INFANTRY), \
        "A3\ui_f\data\map\markers\nato\b_inf.paa" \
    ], \
    [ \
        LOCALIZESTR(MAINTENANCE), \
        "A3\ui_f\data\map\markers\nato\b_maint.paa" \
    ], \
    [ \
        LOCALIZESTR(MECHINF), \
        "A3\ui_f\data\map\markers\nato\b_mech_inf.paa" \
    ], \
    [ \
        LOCALIZESTR(MEDICAL), \
        "A3\ui_f\data\map\markers\nato\b_med.paa" \
    ], \
    [ \
        LOCALIZESTR(MORTAR), \
        "A3\ui_f\data\map\markers\nato\b_mortar.paa" \
    ], \
    [ \
        LOCALIZESTR(MOTINF), \
        "A3\ui_f\data\map\markers\nato\b_motor_inf.paa" \
    ], \
    [ \
        LOCALIZESTR(NAVAL), \
        "A3\ui_f\data\map\markers\nato\b_naval.paa" \
    ], \
    [ \
        LOCALIZESTR(PLANE), \
        "A3\ui_f\data\map\markers\nato\b_plane.paa" \
    ], \
    [ \
        LOCALIZESTR(RECON), \
        "A3\ui_f\data\map\markers\nato\b_recon.paa" \
    ], \
    [ \
        LOCALIZESTR(SUPPORT), \
        "A3\ui_f\data\map\markers\nato\b_support.paa" \
    ], \
    [ \
        LOCALIZESTR(UAV), \
        "A3\ui_f\data\map\markers\nato\b_uav.paa" \
    ], \
    [ \
        LOCALIZESTR(UNKNOWN), \
        "A3\ui_f\data\map\markers\nato\b_unknown.paa" \
    ] \
]

// data for blueforce tracking icons
#define     ICONS_GROUPTYPE         [ \
    [ \
        LOCALIZESTR(HELI), \
        "A3\ui_f\data\map\markers\nato\b_air.paa" \
    ], \
    [ \
        LOCALIZESTR(ARMORED), \
        "A3\ui_f\data\map\markers\nato\b_armor.paa" \
    ], \
    [ \
        LOCALIZESTR(ARTILLERY), \
        "A3\ui_f\data\map\markers\nato\b_art.paa" \
    ], \
    [ \
        LOCALIZESTR(HQ), \
        "A3\ui_f\data\map\markers\nato\b_hq.paa" \
    ], \
    [ \
        LOCALIZESTR(INFANTRY), \
        "A3\ui_f\data\map\markers\nato\b_inf.paa" \
    ], \
    [ \
        LOCALIZESTR(MAINTENANCE), \
        "A3\ui_f\data\map\markers\nato\b_maint.paa" \
    ], \
    [ \
        LOCALIZESTR(MECHINF), \
        "A3\ui_f\data\map\markers\nato\b_mech_inf.paa" \
    ], \
    [ \
        LOCALIZESTR(MEDICAL), \
        "A3\ui_f\data\map\markers\nato\b_med.paa" \
    ], \
    [ \
        LOCALIZESTR(MORTAR), \
        "A3\ui_f\data\map\markers\nato\b_mortar.paa" \
    ], \
    [ \
        LOCALIZESTR(MOTINF), \
        "A3\ui_f\data\map\markers\nato\b_motor_inf.paa" \
    ], \
    [ \
        LOCALIZESTR(NAVAL), \
        "A3\ui_f\data\map\markers\nato\b_naval.paa" \
    ], \
    [ \
        LOCALIZESTR(PLANE), \
        "A3\ui_f\data\map\markers\nato\b_plane.paa" \
    ], \
    [ \
        LOCALIZESTR(RECON), \
        "A3\ui_f\data\map\markers\nato\b_recon.paa" \
    ], \
    [ \
        LOCALIZESTR(SUPPORT), \
        "A3\ui_f\data\map\markers\nato\b_support.paa" \
    ], \
    [ \
        LOCALIZESTR(UAV), \
        "A3\ui_f\data\map\markers\nato\b_uav.paa" \
    ], \
    [ \
        LOCALIZESTR(UNKNOWN), \
        "A3\ui_f\data\map\markers\nato\b_unknown.paa" \
    ] \
]

// data for blueforce tracking group size
#define     ICONS_GROUPSIZE         [ \
    [ \
        LOCALIZESTR(TEAM), \
        "\a3\ui_f\data\map\Markers\NATO\group_1.paa", \
        1 \
    ], \
    [ \
        LOCALIZESTR(SQUAD), \
        "\a3\ui_f\data\map\Markers\NATO\group_2.paa", \
        1.1 \
    ], \
    [ \
        LOCALIZESTR(PLATOON), \
        "\a3\ui_f\data\map\Markers\NATO\group_3.paa", \
        1.2 \
    ], \
    [ \
        LOCALIZESTR(COMPANY), \
        "\a3\ui_f\data\map\Markers\NATO\group_4.paa", \
        1.3 \
    ], \
    [ \
        LOCALIZESTR(TEAM), \
        "\a3\ui_f\data\map\Markers\NATO\group_1.paa", \
        1 \
    ], \
    [ \
        LOCALIZESTR(SQUAD), \
        "\a3\ui_f\data\map\Markers\NATO\group_2.paa", \
        1.1 \
    ], \
    [ \
        LOCALIZESTR(PLATOON), \
        "\a3\ui_f\data\map\Markers\NATO\group_3.paa", \
        1.2 \
    ], \
    [ \
        LOCALIZESTR(COMPANY), \
        "\a3\ui_f\data\map\Markers\NATO\group_4.paa", \
        1.3 \
    ] \
]