class ACE_HuntIR_Propell_Fx {
    class ACE_HuntIR_ExploAmmoFlash {
        simulation = "particles";
        type = "ACE_HuntIR_ExploAmmoFlash";
        position[] = { 0, 0, 0 };
        intensity = 1;
        interval = 1;
        lifeTime = 1;
    };
    class ACE_HuntIR_ExploAmmoSmoke {
        simulation = "particles";
        type = "ACE_HuntIR_ExploAmmoSmoke";
        position[] = { 0, 0, 0 };
        intensity = 1;
        interval = 1;
        lifeTime = 0.8;
    };
};

class CfgCloudlets {
    class Default;
    class ACE_HuntIR_ExploAmmoFlash: Default {
        interval = 0.1;
        circleRadius = 0;
        circleVelocity[] = { 0, 0, 0 };
        particleShape = "\A3\data_f\ParticleEffects\Universal\Universal";
        particleFSNtieth = 16;
        particleFSIndex = 0;
        particleFSFrameCount = 32;
        particleFSLoop = 0;
        angleVar = 1;
        animationName = "";
        particleType = "Billboard";
        timerPeriod = 1;
        lifeTime = 0.5;
        moveVelocity[] = { 0, 1, 0 };
        rotationVelocity = 1;
        weight = 10;
        volume = 7.9;
        rubbing = 0.1;
        size[] = { "0.0125 * intensity + 0.25", "0.0125 * intensity + 0.125" };
        color[] = { { 1, 1, 1, -1 }, { 1, 1, 1, 0 } };
        animationSpeed[] = { 2 };
        randomDirectionPeriod = 0.2;
        randomDirectionIntensity = 0.2;
        onTimerScript = "";
        beforeDestroyScript = "";
        lifeTimeVar = 0;
        positionVar[] = { 0, 0.1, 0 };
        MoveVelocityVar[] = { 0.2, 0.5, 0.2 };
        rotationVelocityVar = 1;
        sizeVar = 0.5;
        colorVar[] = { 0, 0, 0, 0 };
        randomDirectionPeriodVar = 0;
        randomDirectionIntensityVar = 0;
    };
    class ACE_HuntIR_ExploAmmoSmoke: Default {
        interval = "0.02 * interval + 0.02";
        circleRadius = 0;
        circleVelocity[] = { 0, 0, 0 };
        particleShape = "\A3\data_f\ParticleEffects\Universal\Universal";
        particleFSNtieth = 16;
        particleFSIndex = 7;
        particleFSFrameCount = 48;
        particleFSLoop = 1;
        angleVar = 1;
        animationName = "";
        particleType = "Billboard";
        timerPeriod = 1;
        lifeTime = 0.25;
        moveVelocity[] = { 0, 1, 0 };
        rotationVelocity = 1;
        weight = 0.053;
        volume = 0.04;
        rubbing = 0.2;
        size[] = { "0.0125 * intensity + 0.25", "0.0125 * intensity + 1.25", "0.0125 * intensity + 2.75", "0.0125 * intensity + 3.75" };
        color[] = { { 0.6, 0.6, 0.6, 1 }, { 0.7, 0.7, 0.7, 0.5 }, { 0.78, 0.78, 0.78, 0.25 } };
        animationSpeed[] = { 1.7, 0.6, 0.4, 0.3, 0.3 };
        randomDirectionPeriod = 0.2;
        randomDirectionIntensity = 0.2;
        onTimerScript = "";
        beforeDestroyScript = "";
        lifeTimeVar = 2;
        positionVar[] = { 0.5, 0.3, 0.5 };
        MoveVelocityVar[] = { 1.5, 2, 1.5 };
        rotationVelocityVar = 1;
        sizeVar = 0.5;
        colorVar[] = { 0, 0, 0, 0 };
        randomDirectionPeriodVar = 0;
        randomDirectionIntensityVar = 0;
    };
};
