PREP(effectBleeding);
PREP(effectBloodVolume);
PREP(effectHeartBeat);
PREP(effectIncapacitated);
PREP(effectPain);
PREP(effectUnconscious);
PREP(handleEffects);
PREP(initEffects);
PREP(playInjuredSound);
