#define NO_INJURY			-1


/*	FLESH WOUNDS/BLEEDING INJURIES	*/
#define SCRATCH 			0
#define MINOR_OPEN_WOUND 	1
#define MEDIUM_OPEN_WOUND 	2
#define LARGE_OPEN_WOUND 	3
#define MINOR_GSW			4
#define MEDIUM_GSW			5
#define LARGE_GSW			6
#define STOMACH_WOUND		7
#define SCHRAPNEL_WOUND		8
#define GRAZE_WOUND			9
#define MINOR_CUT			10
#define MEDIUM_CUT			11
#define LARGE_CUT			12
#define MISSING_FLESH		13
#define EXPLOSION_WOUND		14

/*	BURN INJURIES	*/
#define MINOR_BURN			40
#define MEDIUM_BURN			41
#define HIGH_BURN			42

/*	INTERNAL BLEEDING	*/
#define MINOR_INTERNAL_BLEEDING		50
#define MEDIUM_INTERNAL_BLEEDING 	51
#define HEAVY_INTERNAL_BLEEDING		52

/*	BROKEN BONES	*/
#define BROKEN_BONE_FEMUR			80
#define BROKEN_BONE_TIBIA			81
#define BROKEN_BONE_HUMERUS			82
#define BROKEN_BONE_RADIAL			83
#define BROKEN_BONE_SKULL			84
#define BROKEN_RIB					85
#define SHATTERED_NECK_BONE			86
#define BROKEN_C_SPINE				87

/*	AIRWAY INJURIES	*/
#define TENSION_PNEUMOTHORA			200
#define SIMPLE_PNEUMOTHORA			201
#define HEMOTHORAX					202
#define AIRWAY_OBSTRUCTION_PARTIAL	205
#define AIRWAY_OBSTRUCTION_FULL		204