#define COMPONENT pylons
#define COMPONENT_BEAUTIFIED Pylons
#include "\z\ace\addons\main\script_mod.hpp"

// #define DEBUG_MODE_FULL
// #define DISABLE_COMPILE_CACHE
// #define ENABLE_PERFORMANCE_COUNTERS

#ifdef DEBUG_ENABLED_PYLONS
    #define DEBUG_MODE_FULL
#endif

#ifdef DEBUG_SETTINGS_PYLONS
    #define DEBUG_SETTINGS DEBUG_SETTINGS_PYLONS
#endif

#include "\z\ace\addons\main\script_macros.hpp"


#define ID_DIALOG 654654
#define ID_TEXT_TITLEBAR 100
#define ID_BACKGROUND_DIALOG 110
#define ID_BACKGROUND_PICTURE 111
#define ID_PICTURE_AIRCRAFT 120
#define ID_CHECKBOX_MIRROR 130
#define ID_TEXT_MIRROR 140
#define ID_CHECKBOX_FRIES 141
#define ID_TEXT_FRIES 142
#define ID_TEXT_LISTTITLE 150
#define ID_LIST_LOADOUTS 160
#define ID_EDIT_LOADOUTNAME 170
#define ID_BUTTON_SAVE 180
#define ID_BUTTON_LOAD 190
#define ID_BUTTON_DELETE 200
#define ID_BUTTON_APPLY 210
#define ID_BUTTON_CLOSE 211
#define ID_TEXT_BANNER 220
