UNIFORM_GLOVES_ROLLED(EF_U_B_MarineCombatUniform_Des_1,EF_U_B_MarineCombatUniform_Des_2,EF_U_B_MarineCombatUniform_Des_6,EF_U_B_MarineCombatUniform_Des_3);
UNIFORM_SLEEVES(EF_U_B_MarineCombatUniform_Des_5,EF_U_B_MarineCombatUniform_Des_4);

UNIFORM_GLOVES_ROLLED(EF_U_B_MarineCombatUniform_Wdl_1,EF_U_B_MarineCombatUniform_Wdl_2,EF_U_B_MarineCombatUniform_Wdl_6,EF_U_B_MarineCombatUniform_Wdl_3);
UNIFORM_SLEEVES(EF_U_B_MarineCombatUniform_Wdl_5,EF_U_B_MarineCombatUniform_Wdl_4);
