// -----------------------------------------------------------------------------
// Automatically generated by 'functions_config.rb'
// DO NOT MANUALLY EDIT THIS FILE!
// -----------------------------------------------------------------------------

class CfgFunctions {
	class ACE {
		class Cargo {
			// ACE_fnc_canLoadCargo
			class canLoadCargo {
				description = "Checks if vehicle is able to load cargo";
				file = "\z\ace\Addons\sys_cargo\fnc_canLoadCargo.sqf";
			};
			// ACE_fnc_listCargo
			class listCargo {
				description = "Lists cargo of a vehicle.";
				file = "\z\ace\Addons\sys_cargo\fnc_listCargo.sqf";
			};
			// ACE_fnc_loadCargo
			class loadCargo {
				description = "Load cargo into vehicles.";
				file = "\z\ace\Addons\sys_cargo\fnc_loadCargo.sqf";
			};
			// ACE_fnc_unloadCargo
			class unloadCargo {
				description = "Unloads cargo from a vehicle.";
				file = "\z\ace\Addons\sys_cargo\fnc_unloadCargo.sqf";
			};
		};
	};
};
