// UNIFORM_SLEEVES(variantSleevesDown,variantSleevesUp);
// UNIFORM_GLOVES(variantGlovesOn,variantGlovesOff);

UNIFORM_GLOVES(U_SPE_FSJ_mk2,U_SPE_FSJ_mk2_gloves);

UNIFORM_SLEEVES(U_SPE_CIV_Worker_Coverall_1,U_SPE_CIV_Worker_Coverall_1_trop);
UNIFORM_SLEEVES(U_SPE_CIV_Worker_Coverall_2,U_SPE_CIV_Worker_Coverall_2_trop);
UNIFORM_SLEEVES(U_SPE_CIV_Worker_Coverall_3,U_SPE_CIV_Worker_Coverall_3_trop);

UNIFORM_SLEEVES(U_SPE_CIV_Worker_1,U_SPE_CIV_Worker_1_trop);
UNIFORM_SLEEVES(U_SPE_CIV_Worker_2,U_SPE_CIV_Worker_2_trop);
UNIFORM_SLEEVES(U_SPE_CIV_Worker_3,U_SPE_CIV_Worker_3_trop);

UNIFORM_SLEEVES(U_SPE_FFI_Worker_1,U_SPE_FFI_Worker_1_trop);
UNIFORM_SLEEVES(U_SPE_FFI_Worker_2,U_SPE_FFI_Worker_2_trop);
UNIFORM_SLEEVES(U_SPE_FFI_Worker_3,U_SPE_FFI_Worker_3_trop);
UNIFORM_SLEEVES(U_SPE_FFI_Worker_4,U_SPE_FFI_Worker_4_trop);

UNIFORM_SLEEVES(U_SPE_FR_Tank_Crew,U_SPE_FR_Tank_Crew3);

UNIFORM_SLEEVES(U_SPE_GER_Schutze_hbt,U_SPE_GER_MG_schutze_hbt);

UNIFORM_SLEEVES(U_SPE_LW_FSJ_base,U_SPE_LW_FSJ_roll);
UNIFORM_SLEEVES(U_SPE_LW_FSJ_mk3,U_SPE_LW_FSJ_mk3_roll);


UNIFORM_SLEEVES(U_SPE_ST_Mix_E44,U_SPE_ST_Mix_E44_roll);
UNIFORM_SLEEVES(U_SPE_ST_Soldier_E44_Boots,U_SPE_ST_Soldier_E44_Boots_rolled);

UNIFORM_SLEEVES(U_SPE_ST_Soldier_E44,U_SPE_ST_MGunner_E44);

//UNIFORM_SLEEVES2(UniformBase,UniformRolled1,UniformRolled2)
//Normal, Offener Kragen, Offener Kragen Ärmel Hoch

UNIFORM_SLEEVES2(U_SPE_GER_Soldier_M36_Boots,U_SPE_GER_Soldier_M36_Boots_open,U_SPE_GER_Soldier_M36_Boots_Rolled);
UNIFORM_SLEEVES2(U_SPE_GER_Soldier_M40_Boots,U_SPE_GER_Soldier_M40_Boots_open,U_SPE_GER_Soldier_M40_Boots_Rolled);
UNIFORM_SLEEVES2(U_SPE_GER_Soldier_M40_Gaiters_closed,U_SPE_GER_Soldier_M40_Gaiters,U_SPE_GER_Soldier_M40_Gaiters_Rolled);
UNIFORM_SLEEVES2(U_SPE_GER_Soldier_Boots,U_SPE_GER_Soldier_Boots_open,U_SPE_GER_Soldier_Boots_Rolled);

UNIFORM_SLEEVES2(U_SPE_GER_Soldier_Gaiters_closed,U_SPE_GER_Soldier_Gaiters,U_SPE_GER_MG_schutze); // Different colored shoes :sob:


UNIFORM_SLEEVES2(U_SPE_LW_base,U_SPE_LW_op,U_SPE_LW_roll);
UNIFORM_SLEEVES2(U_SPE_LW_2,U_SPE_LW_2_op,U_SPE_LW_2_roll);

UNIFORM_SLEEVES2(U_SPE_CSK_base,U_SPE_CSK_op,U_SPE_CSK_roll);
UNIFORM_SLEEVES2(U_SPE_CSK_2,U_SPE_CSK_2_op,U_SPE_CSK_2_roll);

UNIFORM_SLEEVES2(U_SPE_OST_base,U_SPE_OST_op,U_SPE_OST_roll);
UNIFORM_SLEEVES2(U_SPE_OST_2,U_SPE_OST_2_op,U_SPE_OST_2_roll);

UNIFORM_SLEEVES2(U_SPE_ST_Soldier_M36_Boots,U_SPE_ST_Soldier_M36_Boots_open,U_SPE_ST_Soldier_M36_Boots_rolled);

UNIFORM_SLEEVES2(U_SPE_ST_Soldier_M40_Boots,U_SPE_ST_Soldier_M40_Boots_open,U_SPE_ST_Soldier_M40_Boots_rolled);
UNIFORM_SLEEVES2(U_SPE_ST_Soldier_M40_Gaiters_closed,U_SPE_ST_Soldier_M40_Gaiters,U_SPE_ST_Soldier_M40_rolled);

UNIFORM_SLEEVES2(U_SPE_ST_Soldier_Gaiters_closed,U_SPE_ST_Soldier_Gaiters,U_SPE_ST_Soldier_rolled);
UNIFORM_SLEEVES2(U_SPE_ST_Soldier_Boots,U_SPE_ST_Soldier_Boots_open,U_SPE_ST_Soldier_Boots_rolled);

// US
UNIFORM_GLOVES(U_SPE_US_AB_Uniform_M43,U_SPE_US_AB_Uniform_M43_glove);
UNIFORM_GLOVES(U_SPE_US_AB_Uniform_M43_Medic,U_SPE_US_AB_Uniform_M43_glove_Medic);

UNIFORM_GLOVES(U_SPE_US_AB_Uniform_M43_flag,U_SPE_US_AB_Uniform_M43_glove_flag);
UNIFORM_GLOVES(U_SPE_US_AB_Uniform_M43_flag_Medic,U_SPE_US_AB_Uniform_M43_glove_flag_Medic);

UNIFORM_GLOVES(U_SPE_US_AB_Uniform_M43_flag_arm,U_SPE_US_AB_Uniform_M43_glove_flag_arm);
UNIFORM_GLOVES(U_SPE_US_AB_Uniform_M43_flag_arm_Medic,U_SPE_US_AB_Uniform_M43_glove_flag_arm_Medic);


// Normal, Gloves, Rolled
UNIFORM_GLOVES_ROLLED2(U_SPE_US_AB_Uniform_M42,U_SPE_US_AB_Uniform_M42_glove,U_SPE_US_AB_Uniform_M42_roll);
UNIFORM_GLOVES_ROLLED2(U_SPE_US_AB_Uniform_M42_Medic,U_SPE_US_AB_Uniform_M42_Medic_glove,U_SPE_US_AB_Uniform_M42_Medic_roll);

UNIFORM_GLOVES_ROLLED2(U_SPE_US_AB_Uniform_M42_camo,U_SPE_US_AB_Uniform_M42_camo_glove,U_SPE_US_AB_Uniform_M42_camo_roll);
UNIFORM_GLOVES_ROLLED2(U_SPE_US_AB_Uniform_M42_camo_Medic,U_SPE_US_AB_Uniform_M42_camo_Medic_glove,U_SPE_US_AB_Uniform_M42_camo_Medic_roll);

UNIFORM_GLOVES_ROLLED2(U_SPE_US_AB_Uniform_M42_camo_flag,U_SPE_US_AB_Uniform_M42_camo_flag_glove,U_SPE_US_AB_Uniform_M42_camo_flag_roll);
UNIFORM_GLOVES_ROLLED2(U_SPE_US_AB_Uniform_M42_camo_flag_Medic,U_SPE_US_AB_Uniform_M42_camo_flag_Medic_glove,U_SPE_US_AB_Uniform_M42_camo_flag_Medic_roll);


UNIFORM_GLOVES_ROLLED2(U_SPE_US_AB_Uniform_M42_padded_CC2,U_SPE_US_AB_Uniform_M42_padded_CC2_glove,U_SPE_US_AB_Uniform_M42_padded_CC2_roll);
UNIFORM_GLOVES_ROLLED2(U_SPE_US_AB_Uniform_M42_padded_CC2_Medic,U_SPE_US_AB_Uniform_M42_padded_CC2_Medic_glove,U_SPE_US_AB_Uniform_M42_padded_CC2_Medic_roll);
UNIFORM_GLOVES_ROLLED2(U_SPE_US_AB_Uniform_M42_padded_CC2_knife,U_SPE_US_AB_Uniform_M42_padded_CC2_glove_knife,U_SPE_US_AB_Uniform_M42_padded_CC2_roll_knife);
UNIFORM_GLOVES(U_SPE_US_AB_Uniform_M42_padded_CC2_506,U_SPE_US_AB_Uniform_M42_padded_CC2_506_glove);

UNIFORM_GLOVES_ROLLED2(U_SPE_US_AB_Uniform_M42_padded_CC2_flag,U_SPE_US_AB_Uniform_M42_padded_CC2_flag_glove,U_SPE_US_AB_Uniform_M42_padded_CC2_flag_roll);
UNIFORM_GLOVES_ROLLED2(U_SPE_US_AB_Uniform_M42_padded_CC2_flag_Medic,U_SPE_US_AB_Uniform_M42_padded_CC2_flag_Medic_glove,U_SPE_US_AB_Uniform_M42_padded_CC2_flag_Medic_roll);
UNIFORM_GLOVES_ROLLED2(U_SPE_US_AB_Uniform_M42_padded_CC2_flag_knife,U_SPE_US_AB_Uniform_M42_padded_CC2_flag_glove_knife,U_SPE_US_AB_Uniform_M42_padded_CC2_flag_roll_knife);

UNIFORM_GLOVES_ROLLED2(U_SPE_US_AB_Uniform_M42_flag,U_SPE_US_AB_Uniform_M42_flag_glove,U_SPE_US_AB_Uniform_M42_flag_roll);
UNIFORM_GLOVES_ROLLED2(U_SPE_US_AB_Uniform_M42_flag_Medic,U_SPE_US_AB_Uniform_M42_flag_Medic_glove,U_SPE_US_AB_Uniform_M42_flag_Medic_roll);

UNIFORM_GLOVES_ROLLED2(U_SPE_US_AB_Uniform_M42_flag_arm,U_SPE_US_AB_Uniform_M42_flag_arm_glove,U_SPE_US_AB_Uniform_M42_flag_arm_roll);
UNIFORM_GLOVES_ROLLED2(U_SPE_US_AB_Uniform_M42_flag_arm_Medic,U_SPE_US_AB_Uniform_M42_flag_arm_Medic_glove,U_SPE_US_AB_Uniform_M42_flag_arm_Medic_roll);

UNIFORM_GLOVES(U_SPE_US_AB_Uniform_M42_padded_gas,U_SPE_US_AB_Uniform_M42_padded_gas_glove);
UNIFORM_GLOVES(U_SPE_US_AB_Uniform_M42_padded_gas_knife,U_SPE_US_AB_Uniform_M42_padded_gas_glove_knife);
UNIFORM_GLOVES(U_SPE_US_AB_Uniform_M42_padded_gas_Medic,U_SPE_US_AB_Uniform_M42_padded_gas_Medic_glove);
UNIFORM_GLOVES(U_SPE_US_AB_Uniform_M42_padded_gas_506,U_SPE_US_AB_Uniform_M42_padded_gas_506_glove);
UNIFORM_GLOVES(U_SPE_US_AB_Uniform_M42_padded_gas_506_knife,U_SPE_US_AB_Uniform_M42_padded_gas_506_glove_knife);

UNIFORM_GLOVES_ROLLED2(U_SPE_US_AB_Uniform_M42_padded,U_SPE_US_AB_Uniform_M42_padded_glove,U_SPE_US_AB_Uniform_M42_padded_roll);
UNIFORM_GLOVES_ROLLED2(U_SPE_US_AB_Uniform_M42_padded_Medic,U_SPE_US_AB_Uniform_M42_padded_Medic_glove,U_SPE_US_AB_Uniform_M42_padded_Medic_roll);
UNIFORM_GLOVES_ROLLED2(U_SPE_US_AB_Uniform_M42_padded_knife,U_SPE_US_AB_Uniform_M42_padded_glove_knife,U_SPE_US_AB_Uniform_M42_padded_roll_knife);
UNIFORM_GLOVES(U_SPE_US_AB_Uniform_M42_padded_506,U_SPE_US_AB_Uniform_M42_padded_506_glove);

UNIFORM_GLOVES_ROLLED2(U_SPE_US_AB_Uniform_M42_padded_flag,U_SPE_US_AB_Uniform_M42_padded_flag_glove,U_SPE_US_AB_Uniform_M42_padded_flag_roll);
UNIFORM_GLOVES_ROLLED2(U_SPE_US_AB_Uniform_M42_padded_flag_Medic,U_SPE_US_AB_Uniform_M42_padded_flag_Medic_glove,U_SPE_US_AB_Uniform_M42_padded_flag_Medic_roll);
UNIFORM_GLOVES_ROLLED2(U_SPE_US_AB_Uniform_M42_padded_flag_knife,U_SPE_US_AB_Uniform_M42_padded_flag_glove_knife,U_SPE_US_AB_Uniform_M42_padded_flag_roll_knife);

UNIFORM_GLOVES(U_SPE_US_S31_erla,U_SPE_US_S31_erla_glove);
UNIFORM_GLOVES(U_SPE_US_S31A_erla,U_SPE_US_S31A_erla_glove);

UNIFORM_SLEEVES(U_SPE_US_Tank_Coverall,U_SPE_US_Tank_Coverall_Trop);
UNIFORM_SLEEVES(U_SPE_US_Tank_Coverall_Legging,U_SPE_US_Tank_Coverall_Trop_Legging);

UNIFORM_SLEEVES(U_SPE_US_SC_EM,U_SPE_US_SC_EM_roll);

UNIFORM_SLEEVES(U_SPE_US_CC_HBT_camo,U_SPE_US_CC_HBT_camo_roll);
UNIFORM_SLEEVES(U_SPE_US_CC_HBT_camo_trop,U_SPE_US_CC_HBT_camo_trop_roll);

UNIFORM_SLEEVES(U_SPE_US_CC_HBT_EM,U_SPE_US_CC_HBT_EM_roll);

UNIFORM_SLEEVES(U_SPE_US_CC_EM,U_SPE_US_CC_EM_roll);
UNIFORM_SLEEVES(U_SPE_US_CC_EM_trop,U_SPE_US_CC_EM_trop_roll);
UNIFORM_SLEEVES(U_SPE_US_CC_EM_late,U_SPE_US_CC_EM_late_roll);


