// Map position within background, pixel based
#define JV5_MAP_X (685)
#define JV5_MAP_Y (608)
#define JV5_MAP_W (810)
#define JV5_MAP_H (810)

// Height of header and footer OSD elements
#define JV5_OSD_HEADER_H (44)
#define JV5_OSD_FOOTER_H (0)

// Screen content (the stuff that changes, so map area - header and footer)
#define JV5_SCREEN_CONTENT_X (JV5_MAP_X)
#define JV5_SCREEN_CONTENT_Y (JV5_MAP_Y + JV5_OSD_HEADER_H)
#define JV5_SCREEN_CONTENT_W (JV5_MAP_W)
#define JV5_SCREEN_CONTENT_H (JV5_MAP_H - JV5_OSD_HEADER_H - JV5_OSD_FOOTER_H)

// Message element positions in pixels
#define JV5_MESSAGE_MARGIN_OUTER (10)
#define JV5_MESSAGE_MARGIN_INNER (5)

#define JV5_MESSAGE_BUTTON_W (90)
#define JV5_MESSAGE_BUTTON_H (30)

#define JV5_MESSAGE_MESSAGETEXT_FRAME_X (JV5_SCREEN_CONTENT_X + JV5_MESSAGE_MARGIN_OUTER)
#define JV5_MESSAGE_MESSAGETEXT_FRAME_Y (JV5_SCREEN_CONTENT_Y + JV5_MESSAGE_MARGIN_INNER)
#define JV5_MESSAGE_MESSAGETEXT_FRAME_W (JV5_SCREEN_CONTENT_W - JV5_MESSAGE_MARGIN_OUTER * 2)
#define JV5_MESSAGE_MESSAGETEXT_FRAME_H ((JV5_SCREEN_CONTENT_H - JV5_TASKBAR_H - JV5_MESSAGE_MARGIN_INNER * 3) / 2)

#define JV5_MESSAGE_MESSAGELIST_X (JV5_MESSAGE_MESSAGETEXT_FRAME_X + JV5_MESSAGE_MARGIN_INNER)
#define JV5_MESSAGE_MESSAGELIST_Y (JV5_MESSAGE_MESSAGETEXT_FRAME_Y + JV5_MESSAGE_MARGIN_OUTER)
#define JV5_MESSAGE_MESSAGELIST_W ((JV5_MESSAGE_MESSAGETEXT_FRAME_W - JV5_MESSAGE_MARGIN_INNER * 3) / 3)
#define JV5_MESSAGE_MESSAGELIST_H (JV5_MESSAGE_MESSAGETEXT_FRAME_H - JV5_MESSAGE_MARGIN_INNER - JV5_MESSAGE_MARGIN_OUTER)

#define JV5_MESSAGE_MESSAGETEXT_X (JV5_MESSAGE_MESSAGELIST_X + JV5_MESSAGE_MESSAGELIST_W + JV5_MESSAGE_MARGIN_INNER)
#define JV5_MESSAGE_MESSAGETEXT_Y (JV5_MESSAGE_MESSAGELIST_Y)
#define JV5_MESSAGE_MESSAGETEXT_W (JV5_MESSAGE_MESSAGELIST_W * 2)
#define JV5_MESSAGE_MESSAGETEXT_H (JV5_MESSAGE_MESSAGELIST_H - JV5_MESSAGE_MARGIN_INNER - JV5_MESSAGE_BUTTON_H)

#define JV5_MESSAGE_COMPOSE_FRAME_X (JV5_MESSAGE_MESSAGETEXT_FRAME_X)
#define JV5_MESSAGE_COMPOSE_FRAME_Y (JV5_MESSAGE_MESSAGETEXT_FRAME_Y + JV5_MESSAGE_MESSAGETEXT_FRAME_H + JV5_MESSAGE_MARGIN_INNER)
#define JV5_MESSAGE_COMPOSE_FRAME_W (JV5_MESSAGE_MESSAGETEXT_FRAME_W)
#define JV5_MESSAGE_COMPOSE_FRAME_H (JV5_MESSAGE_MESSAGETEXT_FRAME_H)

#define JV5_MESSAGE_PLAYERLIST_X (JV5_MESSAGE_MESSAGELIST_X)
#define JV5_MESSAGE_PLAYERLIST_Y (JV5_MESSAGE_COMPOSE_FRAME_Y + JV5_MESSAGE_MARGIN_OUTER)
#define JV5_MESSAGE_PLAYERLIST_W (JV5_MESSAGE_MESSAGELIST_W)
#define JV5_MESSAGE_PLAYERLIST_H (JV5_MESSAGE_MESSAGELIST_H)

#define JV5_MESSAGE_COMPOSE_TEXT_X (JV5_MESSAGE_MESSAGETEXT_X)
#define JV5_MESSAGE_COMPOSE_TEXT_Y (JV5_MESSAGE_PLAYERLIST_Y)
#define JV5_MESSAGE_COMPOSE_TEXT_W (JV5_MESSAGE_MESSAGETEXT_W)
#define JV5_MESSAGE_COMPOSE_TEXT_H (JV5_MESSAGE_MESSAGETEXT_H)

#define JV5_MESSAGE_BUTTON_SEND_X (JV5_MESSAGE_COMPOSE_FRAME_X + JV5_MESSAGE_COMPOSE_FRAME_W - JV5_MESSAGE_MARGIN_INNER - JV5_MESSAGE_BUTTON_W)
#define JV5_MESSAGE_BUTTON_SEND_Y (JV5_MESSAGE_COMPOSE_TEXT_Y + JV5_MESSAGE_COMPOSE_TEXT_H + JV5_MESSAGE_MARGIN_INNER)

#define JV5_MESSAGE_BUTTON_DELETE_X (JV5_MESSAGE_BUTTON_SEND_X)
#define JV5_MESSAGE_BUTTON_DELETE_Y (JV5_MESSAGE_MESSAGETEXT_Y + JV5_MESSAGE_MESSAGETEXT_H + JV5_MESSAGE_MARGIN_INNER)

// On-screen edge positions (left, right, top, bottom)
#define JV5_OSD_MARGIN (15)
#define JV5_OSD_EDGE_L (JV5_OSD_MARGIN + JV5_SCREEN_CONTENT_X)
#define JV5_OSD_EDGE_R (-JV5_OSD_MARGIN + JV5_SCREEN_CONTENT_X + JV5_SCREEN_CONTENT_W)
#define JV5_OSD_EDGE_T (JV5_OSD_MARGIN + JV5_SCREEN_CONTENT_Y)
#define JV5_OSD_EDGE_B (-JV5_OSD_FOOTER_H + JV5_MAP_Y + JV5_MAP_H)

// On-screen element base width and height
#define JV5_OSD_ELEMENT_STD_W ((JV5_SCREEN_CONTENT_W - JV5_OSD_MARGIN * 6) / 5)
#define JV5_OSD_ELEMENT_STD_H (JV5_OSD_HEADER_H - JV5_OSD_MARGIN)

// On-screen element X-coord for left, center and right elements
#define JV5_OSD_LEFT_X (JV5_OSD_EDGE_L)
#define JV5_OSD_CENTER_X (JV5_OSD_EDGE_L + JV5_OSD_MARGIN + JV5_OSD_ELEMENT_STD_W)
#define JV5_OSD_RIGHT_X (JV5_OSD_EDGE_R - JV5_OSD_ELEMENT_STD_W)

// On-screen element X-coord for left, center and right elements
#define JV5_OSD_X(ITEM) (JV5_OSD_EDGE_L + (JV5_OSD_MARGIN + JV5_OSD_ELEMENT_STD_W) * (ITEM - 1))

// On-screen text sizes, hight in pixels
// Standard text elements
#define JV5_OSD_TEXT_STD_SIZE (24)
#define JV5_OSD_ICON_STD_SIZE (28.5)

// On-screen map centre cursor
#define JV5_CURSOR (76)